<?php
$shippingTotal=(float)($shipping['shipping_total']??0);
$grandTotal=max(0,(float)$cart['total']+$shippingTotal);
?>
<?php if (!empty($removedPaymentBlocked)): ?><div class="container"><div class="settings-note"><span>!</span><p>Removemos <?= (int) $removedPaymentBlocked ?> item(ns) de lojas que não estão habilitadas para receber pagamentos.</p></div></div><?php endif; ?>
<nav class="commerce-breadcrumb container" aria-label="Navegação estrutural"><a href="<?=e(url('/'))?>">Início</a><span>›</span><strong>Carrinho</strong></nav>
<section class="cart-heading container"><div><span class="eyebrow"><?=($cart['type']??'retail')==='wholesale'?'COMPRA EMPRESARIAL':'SUA COMPRA'?></span><h1><?=($cart['type']??'retail')==='wholesale'?'Carrinho atacadista':'Seu carrinho'?></h1><p><?=$cart['count']?> <?=$cart['count']===1?'item':'itens'?> de <?=count($cart['groups'])?> <?=count($cart['groups'])===1?'loja':'lojas'?>.</p></div><div class="cart-mode-actions"><a href="<?=e(url('/produtos'))?>">← Continuar comprando</a><?php if(($cart['type']??'retail')==='wholesale'):?><form method="post" action="<?=e(url('/carrinho/modo'))?>"><?=csrf_field()?><input type="hidden" name="mode" value="retail"><button>Voltar ao modo varejo</button></form><?php endif;?></div></section>
<?php if(($cart['type']??'retail')==='wholesale'):?><div class="wholesale-cart-notice container"><strong>Você está comprando no atacado</strong><span>O carrinho de varejo permanece separado.</span></div><?php endif;?>
<?php if(!$cart['items']):?>
<section class="cart-empty container"><div class="empty-illustration">T</div><h2>Seu carrinho está vazio.</h2><p>Explore produtos selecionados de lojas oficiais.</p><a class="button button--primary" href="<?=e(url('/produtos'))?>">Explorar produtos</a></section>
<?php else:?>
<div class="cart-layout cart-container container"><div class="cart-content"><div class="cart-stores">
<?php foreach($cart['groups'] as $group):$storeShipping=$shipping['stores'][(int)$group['store_id']]??null;$selectedQuote=$storeShipping['options'][0]??null;?><section class="cart-store"><header><div><span>Vendido e enviado por</span><a href="<?=e(url('/loja/'.$group['store_slug']))?>"><?=e($group['store_name'])?></a></div><b><?=count($group['items'])?> <?=count($group['items'])===1?'produto':'produtos'?></b></header>
<?php foreach($group['items'] as $item):$minQty=($cart['type']??'retail')==='wholesale'?max(1,(int)$item['wholesale_min_quantity']):1;?><article class="cart-item">
<a class="cart-item__image" href="<?=e(url('/produto/'.$item['slug']))?>"><?php if($item['image_url']):?><img src="<?=e($item['image_url'])?>" alt="<?=e($item['name'])?>"><?php else:?><span class="product-placeholder"><b>TUFFER</b></span><?php endif;?></a>
<div class="cart-item__info"><span class="cart-item__seller"><?=e($group['store_name'])?></span><a href="<?=e(url('/produto/'.$item['slug']))?>"><h2><?=e($item['name'])?></h2></a><div class="cart-item__details"><?php if((int)$item['package_count']>1):?><span>Kit com <?=(int)$item['package_count']?> unidades</span><?php endif;?><?php if($item['variant_name']&&mb_strtolower($item['variant_name'])!=='padrão'):?><span>Variação: <?=e($item['variant_name'])?></span><?php endif;?><?php foreach(array_slice($item['specification_rows'],0,3) as $specification):?><span><?=e($specification)?></span><?php endforeach;?><span>SKU: <?=e($item['sku'])?></span><span>Compra: <?=$cart['type']==='wholesale'?'atacado':'varejo'?></span><span><?=(int)$item['available']?> disponíveis</span></div><div class="cart-item__links"><form action="<?=e(url('/carrinho/item/'.$item['id']))?>" method="post"><?=csrf_field()?><input type="hidden" name="_method" value="DELETE"><button class="remove-item">Remover</button></form><?php if(($authUser['type']??null)==='customer'):?><form action="<?=e(url('/carrinho/item/'.$item['id'].'/salvar'))?>" method="post"><?=csrf_field()?><button>Salvar para depois</button></form><?php endif;?></div></div>
<div class="cart-item__quantity"><span>Quantidade</span><form action="<?=e(url('/carrinho/item/'.$item['id']))?>" method="post"><?=csrf_field()?><input type="hidden" name="_method" value="PUT"><div class="quantity-stepper"><button name="quantity" value="<?=max($minQty,(int)$item['quantity']-1)?>" <?=(int)$item['quantity']<=$minQty?'disabled':''?> aria-label="Diminuir quantidade">−</button><output><?=(int)$item['quantity']?></output><button name="quantity" value="<?=min((int)$item['available'],(int)$item['quantity']+1)?>" <?=(int)$item['quantity']>=(int)$item['available']?'disabled':''?> aria-label="Aumentar quantidade">+</button></div></form></div>
<div class="cart-item__price"><small>R$ <?=number_format((float)$item['piece_price'],2,',','.')?> por unidade</small><span>Total</span><strong>R$ <?=number_format((float)$item['line_total'],2,',','.')?></strong></div></article><?php endforeach;?>
<footer><div><span>Subtotal da loja</span><?php if($group['coupon']):?><small>Cupom <?=e($group['coupon']['code'])?>: − R$ <?=number_format((float)$group['discount'],2,',','.')?></small><?php endif;?></div><strong>R$ <?=number_format((float)$group['subtotal']-(float)$group['discount'],2,',','.')?></strong></footer><?php if($cart['type']==='wholesale'&&!$group['minimum_met']):?><div class="store-minimum-warning">Complete o mínimo da loja<?php if($group['minimum_quantity']):?>: <?=$group['minimum_quantity']?> unidades<?php endif;?><?php if($group['minimum_total']):?> · R$ <?=number_format((float)$group['minimum_total'],2,',','.')?><?php endif;?></div><?php endif;?></section><?php endforeach;?></div>
<section class="cart-delivery-card"><div><span class="eyebrow">ENTREGA</span><h2>Calcule a entrega</h2><p>Consulte valores e prazos reais por loja.</p></div><form method="post" action="<?=e(url('/carrinho/frete'))?>"><?=csrf_field()?><label>CEP<input name="postal_code" data-mask="cep" inputmode="numeric" placeholder="00000-000" value="<?=e($cart['postal_code']??'')?>" required></label><button class="button button--dark">Calcular</button></form><?php if($cart['postal_code']):?><div class="cart-shipping-results"><?php foreach($cart['groups'] as $group):$state=$shipping['stores'][(int)$group['store_id']]??null;$quote=$state['options'][0]??null;?><div><strong><?=e($group['store_name'])?></strong><?php if($quote):?><span><?=e($quote['carrier'].' '.$quote['service'])?></span><b>R$ <?=number_format((float)$quote['price'],2,',','.')?></b><small>Chega entre <?=e($quote['arrival_min'])?> e <?=e($quote['arrival_max'])?></small><?php else:?><small><?=e($state['message']??$shipping['message']??'Cotação indisponível.')?></small><?php endif;?></div><?php endforeach;?></div><?php endif;?></section>
</div>
<aside class="order-summary cart-summary"><h2>Resumo do pedido</h2><div class="coupon-block"><strong>Possui um cupom?</strong><?php $hasCoupon=false;foreach($cart['groups'] as $group)if($group['coupon'])$hasCoupon=true;?><?php if($hasCoupon):?><?php foreach($cart['groups'] as $group):if(!$group['coupon'])continue;?><div class="applied-coupon"><span><b>✓ <?=e($group['coupon']['code'])?> aplicado</b><small><?=e($group['store_name'])?></small></span><form method="post" action="<?=e(url('/carrinho/cupom/'.$group['store_id']))?>"><?=csrf_field()?><input type="hidden" name="_method" value="DELETE"><button aria-label="Remover cupom">×</button></form></div><?php endforeach;?><?php else:?><form method="post" action="<?=e(url('/carrinho/cupom'))?>"><?=csrf_field()?><input name="code" maxlength="60" placeholder="Código do cupom" required><button>Aplicar</button></form><?php endif;?></div><dl><div><dt>Produtos</dt><dd>R$ <?=number_format((float)$cart['subtotal'],2,',','.')?></dd></div><div class="discount-row"><dt>Descontos</dt><dd>− R$ <?=number_format((float)$cart['discount_total'],2,',','.')?></dd></div><div><dt>Entrega</dt><dd><?=$shippingTotal>0?'R$ '.number_format($shippingTotal,2,',','.'):'Calcular'?></dd></div></dl><div class="order-summary__total"><span>Total</span><strong>R$ <?=number_format($grandTotal,2,',','.')?></strong><small>ou 3x de R$ <?=number_format($grandTotal/3,2,',','.')?> sem juros</small></div><?php if($cart['minimums_met']):?><a class="button button--primary button--block" href="<?=e(url('/checkout'))?>">Ir para o checkout</a><?php else:?><button class="button button--secondary button--block" disabled>Complete os mínimos</button><?php endif;?><div class="summary-security"><span>✓ Compra segura</span><span>✓ Pagamento protegido</span><span>✓ Dados criptografados</span></div></aside></div>
<div class="mobile-cart-action"><span><small>Total</small><strong>R$ <?=number_format($grandTotal,2,',','.')?></strong></span><a class="button button--primary" href="<?=e(url('/checkout'))?>">Continuar</a></div>
<?php endif;?>
