<?php

declare(strict_types=1);

namespace App\Http\Controllers\Customer;

use App\Core\Auth;use App\Core\Database;use App\Core\Response;use App\Core\Session;use App\Http\Controllers\Controller;

final class ChatController extends Controller
{
    public function index(): string{$s=Database::connection()->prepare('SELECT c.*,st.name store_name,(SELECT body FROM messages m WHERE m.conversation_id=c.id ORDER BY m.id DESC LIMIT 1) last_message FROM conversations c JOIN stores st ON st.id=c.store_id WHERE c.customer_id=? ORDER BY COALESCE(c.last_message_at,c.created_at) DESC');$s->execute([Auth::id()]);return $this->page('customer/messages/index','layouts/customer',['pageTitle'=>'Mensagens','conversations'=>$s->fetchAll()]);}
    public function create(string $storeId): string{$s=Database::connection()->prepare("SELECT id,name FROM stores WHERE id=? AND status='active'");$s->execute([(int)$storeId]);return $this->page('customer/messages/create','layouts/customer',['pageTitle'=>'Nova mensagem','store'=>$s->fetch()]);}
    public function store(): string{$pdo=Database::connection();$store=$pdo->prepare("SELECT id FROM stores WHERE id=? AND status='active'");$store->execute([(int)($_POST['store_id']??0)]);$subject=trim((string)($_POST['subject']??''));$body=trim((string)($_POST['body']??''));if(!$store->fetchColumn()||$subject===''||$body===''){Session::flash('error','Loja, assunto e mensagem são obrigatórios.');return Response::redirect('/minha-conta/mensagens');}$pdo->beginTransaction();try{$pdo->prepare("INSERT INTO conversations(customer_id,store_id,subject,status,last_message_at) VALUES(?,?,?,'open',NOW())")->execute([Auth::id(),(int)$_POST['store_id'],$subject]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO messages(conversation_id,sender_id,body) VALUES(?,?,?)')->execute([$id,Auth::id(),$body]);$pdo->commit();Session::flash('success','Mensagem enviada.');return Response::redirect('/minha-conta/mensagens/'.$id);}catch(\Throwable){$pdo->rollBack();Session::flash('error','Não foi possível enviar a mensagem.');return Response::redirect('/minha-conta/mensagens');}}
    public function show(string $id): string{$conversation=$this->conversation((int)$id);$s=Database::connection()->prepare('SELECT m.*,u.name sender_name,u.type sender_type FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.conversation_id=? ORDER BY m.created_at');$s->execute([(int)$id]);Database::connection()->prepare('UPDATE messages SET read_at=NOW() WHERE conversation_id=? AND sender_id<>? AND read_at IS NULL')->execute([(int)$id,Auth::id()]);return $this->page('customer/messages/show','layouts/customer',['pageTitle'=>$conversation['subject'],'conversation'=>$conversation,'messages'=>$s->fetchAll()]);}
    public function send(string $id): string{$conversation=$this->conversation((int)$id);if($conversation['status']!=='open'){Session::flash('error','Conversa encerrada.');return Response::redirect('/minha-conta/mensagens/'.$id);}Database::connection()->prepare('INSERT INTO messages(conversation_id,sender_id,body) VALUES(?,?,?)')->execute([(int)$id,Auth::id(),trim((string)$_POST['body'])]);Database::connection()->prepare('UPDATE conversations SET last_message_at=NOW() WHERE id=?')->execute([(int)$id]);return Response::redirect('/minha-conta/mensagens/'.$id);}
    private function conversation(int $id): array{$s=Database::connection()->prepare('SELECT c.*,st.name store_name FROM conversations c JOIN stores st ON st.id=c.store_id WHERE c.id=? AND c.customer_id=?');$s->execute([$id,Auth::id()]);$data=$s->fetch();if(!$data){http_response_code(403);exit('Acesso negado.');}return $data;}
}
