<?php
$sectionLabels = ['identidade'=>'Identidade','aparencia'=>'Aparência','banners'=>'Banners','seo'=>'SEO','comunicacao'=>'Comunicação','integracoes'=>'Integrações','regras'=>'Regras da plataforma','financeiro'=>'Financeiro','seguranca'=>'Segurança'];
$sectionIcons = ['identidade'=>'◈','aparencia'=>'◐','banners'=>'▧','seo'=>'⌕','comunicacao'=>'✉','integracoes'=>'⌁','regras'=>'⚙','financeiro'=>'◫','seguranca'=>'⌾'];
$value = static fn(string $key, mixed $default = ''): mixed => $settings[$key] ?? $default;
$colorValue = static function(string $key, string $fallback) use ($settings): string {
    $candidate = (string) ($settings[$key] ?? '');
    return preg_match('/^#[0-9A-Fa-f]{6}$/', $candidate) ? strtoupper($candidate) : $fallback;
};
$selected = static fn(string $key, string $option, string $default = ''): string => (string) ($settings[$key] ?? $default) === $option ? ' selected' : '';
$checked = static fn(string $key, string $default = '0'): string => (string) ($settings[$key] ?? $default) === '1' ? ' checked' : '';
$uploadMeta = [
    'logo_path'=>['Logo principal','Aparece no cabeçalho sobre fundos claros.','600 × 200 px','2 MB','logo','Logo atual'],
    'logo_dark_path'=>['Logo invertida','Versão clara para fundos escuros.','600 × 200 px','2 MB','logo-dark','Logo invertida atual'],
    'favicon_path'=>['Ícone do navegador','Usado nas abas e favoritos do navegador.','128 × 128 px','1 MB','favicon','Ícone atual'],
    'share_image_path'=>['Imagem de compartilhamento','Prévia padrão para redes sociais e mensageiros.','1200 × 630 px','4 MB','share','Imagem atual'],
    'home_main_banner'=>['Banner principal','Destaque principal da página inicial.','1920 × 720 px','10 MB','home-main','Banner principal atual'],
    'home_discount_banner'=>['Banner de ofertas','Campanhas e promoções em destaque.','1200 × 500 px','10 MB','home-discount','Banner de ofertas atual'],
    'home_official_banner'=>['Banner da loja oficial','Área promocional da loja oficial.','1200 × 500 px','10 MB','home-official','Banner da loja oficial atual'],
    'official_wide_banner'=>['Banner horizontal','Faixa ampla para comunicação institucional.','1920 × 480 px','10 MB','official-wide','Banner horizontal atual'],
];
$uploadCard = static function(string $field, array $meta, array $settings, bool $wide = false): void {
    [$title,$description,$dimensions,$maximum,$previewKey,$alt] = $meta;
    $current = trim((string) ($settings[$field] ?? ''));
    $maxBytes = match($maximum){'1 MB'=>1048576,'2 MB'=>2097152,'4 MB'=>4194304,default=>10485760};
    $linkField = $field . '_link';
    $linkDefaults = ['home_main_banner_link'=>'/produtos','home_discount_banner_link'=>'/ofertas','home_official_banner_link'=>'/lojas','official_wide_banner_link'=>'/lojas'];
    $linkValue = (string) ($settings[$linkField] ?? ($linkDefaults[$linkField] ?? ''));
    ?>
    <article class="platform-upload<?= $wide ? ' platform-upload--wide' : '' ?>" tabindex="0" data-platform-upload data-preview-key="<?= e($previewKey) ?>">
        <div class="platform-upload__preview" data-upload-preview><?php if($current!==''):?><img src="<?=e(upload_asset($current))?>" alt="<?=e($alt)?>"><?php else:?><span>Imagem não enviada</span><?php endif;?></div>
        <div class="platform-upload__content"><strong><?=e($title)?></strong><p><?=e($description)?></p><small>PNG, JPG ou WebP · recomendado <?=e($dimensions)?> · máximo <?=e($maximum)?></small><span data-upload-filename><?= $current!=='' ? 'Imagem atual configurada' : 'Nenhum arquivo selecionado' ?></span><div class="platform-upload__actions"><label class="button button--secondary">Substituir imagem<input type="file" name="upload_<?=e($field)?>" accept="image/jpeg,image/png,image/webp,image/gif,image/x-icon" hidden data-upload-input data-max-bytes="<?=$maxBytes?>"></label><button class="text-button" type="button" data-remove-upload<?= $current==='' ? ' hidden' : '' ?>>Remover</button><input type="hidden" name="remove_<?=e($field)?>" value="0" data-remove-value></div></div>
        <?php if($wide):?><label class="platform-upload__link"><span>Link de destino</span><input type="text" name="<?=e($linkField)?>" maxlength="1000" value="<?=e($linkValue)?>" placeholder="/ofertas ou https://exemplo.com"><small>Use <b>/caminho</b> para páginas internas ou uma URL completa para sites externos.</small></label><?php endif;?>
        <div class="platform-upload__drop-hint">Arraste, solte ou cole com Ctrl + V</div>
    </article>
    <?php
};
$primary = $colorValue('primary_color','#D20A16');
$secondary = $colorValue('secondary_color','#080808');
$accent = $colorValue('accent_color','#AA8A46');
?>
<div class="platform-settings" data-platform-settings-page>
    <header class="platform-settings__header">
        <div><span class="eyebrow">PLATAFORMA</span><h2>Configurações da plataforma</h2><p>Gerencie identidade, comunicação, integrações e regras gerais.</p></div>
        <div class="platform-settings__header-actions"><span class="unsaved-indicator" data-unsaved-indicator hidden><i></i> Alterações não salvas</span><button class="button button--secondary" type="button" data-settings-discard disabled>Descartar</button><button class="button button--primary" form="platform-settings-form" data-settings-submit>Salvar alterações</button></div>
    </header>

    <nav class="platform-settings__tabs" aria-label="Áreas das configurações">
        <?php foreach($sectionLabels as $key=>$label):?><a class="<?=$section===$key?'is-active':''?>" href="<?=e(url('/admin/configuracoes?secao='.$key))?>" <?=$section===$key?'aria-current="page"':''?>><span><?=e($sectionIcons[$key])?></span><b><?=e($label)?></b></a><?php endforeach;?>
    </nav>

    <form id="platform-settings-form" class="platform-settings__form" method="post" enctype="multipart/form-data" action="<?=e(url('/admin/configuracoes'))?>" data-platform-settings-form>
        <?=csrf_field()?><input type="hidden" name="_method" value="PUT"><input type="hidden" name="section" value="<?=e($section)?>">

        <?php if($section==='identidade'):?>
        <div class="platform-settings__layout">
            <div class="platform-settings__main">
                <section class="platform-settings-card"><header><span>01</span><div><h3>Essência da marca</h3><p>Informações exibidas nos principais pontos de contato com o cliente.</p></div></header><div class="platform-fields">
                    <label class="platform-field">Nome da plataforma<input name="platform_name" required maxlength="100" value="<?=e($value('platform_name','Tuffer'))?>" data-preview-name><small>Nome usado no cabeçalho, títulos e comunicações.</small></label>
                    <label class="platform-field">Slogan<input name="slogan" maxlength="160" value="<?=e($value('slogan','Loja Oficial'))?>" data-preview-slogan><small>Uma frase curta para reforçar o posicionamento.</small></label>
                    <label class="platform-field platform-field--full">Descrição curta<textarea name="tagline" rows="4" maxlength="320" data-preview-description><?=e($value('tagline','Um marketplace feito para comprar de quem faz.'))?></textarea><small>Utilizada em áreas institucionais e prévias da plataforma.</small></label>
                </div></section>
                <section class="platform-settings-card"><header><span>02</span><div><h3>Arquivos da identidade</h3><p>As imagens são organizadas automaticamente. Caminhos técnicos não são exibidos.</p></div></header><div class="platform-upload-grid"><?php foreach(['logo_path','logo_dark_path','favicon_path','share_image_path'] as $field)$uploadCard($field,$uploadMeta[$field],$settings);?></div></section>
            </div>
            <aside class="platform-preview" style="--preview-primary:<?=e($primary)?>;--preview-secondary:<?=e($secondary)?>;--preview-accent:<?=e($accent)?>" data-platform-preview>
                <span class="eyebrow">PRÉVIA DA PLATAFORMA</span><div class="platform-preview__browser"><div><i data-preview-favicon><?php if($value('favicon_path')):?><img src="<?=e(upload_asset((string)$value('favicon_path')))?>" alt=""><?php else:?>T<?php endif;?></i><span>tuffer.com.br</span><b>•••</b></div><header><span data-preview-logo><?php if($value('logo_path')):?><img src="<?=e(upload_asset((string)$value('logo_path')))?>" alt=""><?php else:?>TUFFER<?php endif;?></span><nav>Ofertas &nbsp; Produtos &nbsp; Lojas</nav></header><main><small data-preview-slogan><?=e($value('slogan','LOJA OFICIAL'))?></small><h3 data-preview-name><?=e($value('platform_name','Tuffer'))?></h3><p data-preview-description><?=e($value('tagline','Um marketplace feito para comprar de quem faz.'))?></p><button type="button">Explorar produtos</button></main></div><p>Esta prévia é ilustrativa. O conteúdo público utiliza as configurações após o salvamento.</p>
            </aside>
        </div>
        <?php elseif($section==='aparencia'):?>
        <div class="platform-settings__layout"><div class="platform-settings__main"><section class="platform-settings-card"><header><span>01</span><div><h3>Cores da interface</h3><p>Defina uma paleta consistente para botões, destaques e áreas institucionais.</p></div></header><div class="platform-fields platform-fields--three">
            <?php foreach([['primary_color','Cor principal',$primary],['secondary_color','Cor secundária',$secondary],['accent_color','Cor de destaque',$accent]] as [$name,$label,$color]):?><label class="platform-field platform-color-field"><?=e($label)?><span><input type="color" value="<?=e($color)?>" data-color-picker><input name="<?=e($name)?>" pattern="#[0-9A-Fa-f]{6}" value="<?=e($color)?>" data-color-text></span></label><?php endforeach;?>
        </div></section><section class="platform-settings-card"><header><span>02</span><div><h3>Estilo visual</h3><p>Ajustes globais para a experiência da marca.</p></div></header><div class="platform-fields">
            <label class="platform-field">Modo de cor<select name="color_mode"><option value="light"<?=$selected('color_mode','light','light')?>>Claro</option><option value="dark"<?=$selected('color_mode','dark')?>>Escuro</option><option value="automatic"<?=$selected('color_mode','automatic')?>>Automático conforme o dispositivo</option></select></label>
            <label class="platform-field">Tipografia<select name="typography"><option value="editorial"<?=$selected('typography','editorial','editorial')?>>Editorial</option><option value="modern"<?=$selected('typography','modern')?>>Moderna</option><option value="system"<?=$selected('typography','system')?>>Sistema</option></select></label>
            <label class="platform-field">Estilo dos botões<select name="button_style" data-button-style><option value="rounded"<?=$selected('button_style','rounded','rounded')?>>Arredondado</option><option value="soft"<?=$selected('button_style','soft')?>>Suave</option><option value="square"<?=$selected('button_style','square')?>>Reto</option></select></label>
        </div></section></div><aside class="platform-preview" style="--preview-primary:<?=e($primary)?>;--preview-secondary:<?=e($secondary)?>;--preview-accent:<?=e($accent)?>" data-platform-preview><span class="eyebrow">PRÉVIA DA LOJA</span><div class="appearance-preview"><div class="appearance-preview__nav"><b><?=e($value('platform_name','Tuffer'))?></b><span>Buscar produtos</span></div><main><small>NOVIDADES</small><h3>Sua vitrine, com a sua identidade.</h3><p>Cores e botões são atualizados enquanto você edita.</p><button type="button" data-preview-button>Ver coleção</button></main><footer><i></i><i></i><i></i></footer></div></aside></div>
        <?php elseif($section==='banners'):?>
        <section class="platform-settings-card"><header><span>01</span><div><h3>Banners da plataforma</h3><p>Imagens promocionais da página inicial e áreas institucionais.</p></div></header><div class="platform-upload-grid platform-upload-grid--banners"><?php foreach(['home_main_banner','home_discount_banner','home_official_banner','official_wide_banner'] as $field)$uploadCard($field,$uploadMeta[$field],$settings,true);?></div></section>
        <?php elseif($section==='seo'):?>
        <div class="platform-settings__layout"><div class="platform-settings__main"><section class="platform-settings-card"><header><span>01</span><div><h3>Presença nos buscadores</h3><p>Controle como a página principal aparece nos resultados de pesquisa.</p></div></header><div class="platform-fields"><label class="platform-field platform-field--full">Título SEO<input name="seo_title" maxlength="190" value="<?=e($value('seo_title','Tuffer Marketplace'))?>" data-seo-title></label><label class="platform-field platform-field--full">Descrição SEO<textarea name="seo_description" rows="4" maxlength="320" data-seo-description><?=e($value('seo_description',''))?></textarea></label><label class="platform-field platform-field--full">Palavras-chave<input name="seo_keywords" maxlength="320" value="<?=e($value('seo_keywords',''))?>"><small>Separe termos relevantes por vírgula.</small></label><label class="platform-field">Indexação<select name="seo_robots"><option value="index,follow"<?=$selected('seo_robots','index,follow','index,follow')?>>Indexar página e links</option><option value="noindex,follow"<?=$selected('seo_robots','noindex,follow')?>>Não indexar a página</option><option value="noindex,nofollow"<?=$selected('seo_robots','noindex,nofollow')?>>Não indexar página nem links</option></select></label></div></section></div><aside class="search-preview"><span class="eyebrow">PRÉVIA NO GOOGLE</span><div><small>https://tuffer.com.br</small><h3 data-seo-title-preview><?=e($value('seo_title','Tuffer Marketplace'))?></h3><p data-seo-description-preview><?=e($value('seo_description','Conheça produtos, ofertas e lojas selecionadas na Tuffer.'))?></p></div><p>O buscador pode adaptar o conteúdo conforme a consulta.</p></aside></div>
        <?php elseif($section==='comunicacao'):?>
        <section class="platform-settings-card"><header><span>01</span><div><h3>Identificação e canais públicos</h3><p>Dados exibidos nas políticas, no atendimento e nos documentos institucionais.</p></div></header><div class="platform-fields"><label class="platform-field">Razão social ou responsável legal<input name="legal_name" value="<?=e($value('legal_name',''))?>" autocomplete="organization"></label><label class="platform-field">CPF ou CNPJ<input name="tax_id" value="<?=e($value('tax_id',''))?>" inputmode="numeric"></label><label class="platform-field">E-mail de suporte<input type="email" name="support_email" value="<?=e($value('support_email',''))?>" autocomplete="email"></label><label class="platform-field">E-mail de privacidade<input type="email" name="privacy_email" value="<?=e($value('privacy_email',''))?>" autocomplete="email"><small>Canal para solicitações relacionadas à LGPD.</small></label><label class="platform-field">Alerta de nova venda<input type="email" name="new_sale_alert_email" value="<?=e($value('new_sale_alert_email',''))?>" autocomplete="email"><small>Recebe um aviso quando o pagamento do pedido for confirmado.</small></label><label class="platform-field">Telefone<input name="support_phone" value="<?=e($value('support_phone',''))?>" autocomplete="tel" placeholder="(11) 3000-0000"></label><label class="platform-field">WhatsApp<input name="whatsapp" value="<?=e($value('whatsapp',''))?>" placeholder="5511999999999"></label><label class="platform-field">Instagram<input name="instagram" value="<?=e($value('instagram',''))?>" placeholder="@tuffer"></label><label class="platform-field">Facebook<input name="facebook" value="<?=e($value('facebook',''))?>" placeholder="facebook.com/tuffer"></label><label class="platform-field">LinkedIn<input name="linkedin" value="<?=e($value('linkedin',''))?>" placeholder="linkedin.com/company/tuffer"></label><label class="platform-field platform-field--full">Endereço comercial<textarea name="business_address" rows="3"><?=e($value('business_address',''))?></textarea></label><label class="platform-field platform-field--full">Horários de atendimento<textarea name="support_hours" rows="3" placeholder="Segunda a sexta, das 9h às 18h"><?=e($value('support_hours',''))?></textarea></label></div></section>
        <?php elseif($section==='integracoes'):?>
        <section class="platform-settings-card"><header><span>01</span><div><h3>Serviços conectados</h3><p>Ative somente integrações com credenciais já configuradas no ambiente.</p></div></header><div class="integration-settings-grid"><?php foreach([['cloudinary_enabled','Cloudinary','Armazenamento e otimização das mídias de produtos.'],['pagarme_enabled','Pagar.me','Criação de pagamentos e processamento de webhooks.'],['melhor_envio_enabled','Melhor Envio','Cotações e rastreamento de entregas.'],['mail_enabled','E-mail transacional','Mensagens enviadas pela fila SMTP.']] as [$name,$label,$description]):?><label class="integration-setting"><span><b><?=e($label)?></b><small><?=e($description)?></small></span><input type="hidden" name="<?=e($name)?>" value="0"><input type="checkbox" name="<?=e($name)?>" value="1"<?=$checked($name)?>><i></i></label><?php endforeach;?></div><div class="settings-security-note"><span>i</span><p>As chaves e senhas permanecem protegidas no arquivo de ambiente e nunca são exibidas nesta tela.</p></div></section>
        <?php elseif($section==='regras'):?>
        <section class="platform-settings-card"><header><span>01</span><div><h3>Operação do marketplace</h3><p>Regras gerais aplicadas a pedidos, vendedores e manutenção.</p></div></header><div class="platform-fields"><label class="platform-field">Comissão padrão (%)<input type="number" name="default_commission" min="0" max="100" step="0.01" value="<?=e($value('default_commission','10.00'))?>"></label><label class="platform-field">Prefixo dos pedidos<input name="orders_prefix" maxlength="12" value="<?=e($value('orders_prefix','TF'))?>" placeholder="TF"><small>Somente letras, números e hífen.</small></label><label class="integration-setting platform-field--full"><span><b>Modo manutenção</b><small>Suspende temporariamente a operação pública da plataforma.</small></span><input type="hidden" name="maintenance_mode" value="0"><input type="checkbox" name="maintenance_mode" value="1"<?=$checked('maintenance_mode')?>><i></i></label></div></section>
        <?php elseif($section==='financeiro'):?>
        <section class="platform-settings-card"><header><span>01</span><div><h3>Arquitetura financeira</h3><p>Identificação explícita da loja oficial, reservas e fechamento. Nenhuma transferência bancária é executada pelo sistema.</p></div></header><div class="platform-fields">
            <label class="platform-field">Seller da loja oficial<select name="official_store_seller_id" required><option value="">Selecione</option><?php foreach($sellerOptions as $seller):?><option value="<?=(int)$seller['id']?>" <?=((string)$value('official_store_seller_id','')===(string)$seller['id']||(int)$seller['is_official_store']===1)?'selected':''?>><?=e($seller['trade_name'].' · '.$seller['status'])?></option><?php endforeach;?></select><small>A identificação não depende de nome, slug ou ID fixo no código.</small></label>
            <label class="platform-field">Reserva percentual (%)<input type="number" name="official_store_reserve_percentage" min="0" max="100" step="0.01" value="<?=e($value('official_store_reserve_percentage','5.00'))?>"></label>
            <label class="platform-field">Reserva mínima (R$)<input type="number" name="official_store_reserve_min_amount" min="0" step="0.01" value="<?=e(number_format(((int)$value('official_store_reserve_min_amount',0))/100,2,'.',''))?>"></label>
            <label class="platform-field">Frequência<select name="official_store_settlement_frequency"><option value="monthly" selected>Mensal</option></select></label>
            <label class="platform-field">Versão da política<input name="marketplace_financial_policy_version" maxlength="50" value="<?=e($value('marketplace_financial_policy_version','marketplace-ledger-v1'))?>"></label>
            <label class="integration-setting platform-field--full"><span><b>Permitir registro de transferência manual</b><small>Registra contabilmente uma transferência já realizada fora da Tuffer. Não movimenta dinheiro.</small></span><input type="hidden" name="official_store_transfer_enabled" value="0"><input type="checkbox" name="official_store_transfer_enabled" value="1"<?=$checked('official_store_transfer_enabled')?>><i></i></label>
        </div></section>
        <?php else:?>
        <div class="platform-settings__layout"><div class="platform-settings__main"><section class="platform-settings-card"><header><span>01</span><div><h3>Proteção administrativa</h3><p>Políticas aplicadas às contas com acesso ao painel.</p></div></header><div class="platform-fields"><label class="platform-field">Expiração da sessão administrativa<select name="admin_session_timeout"><?php foreach([15,30,60,120,240,480] as $minutes):?><option value="<?=$minutes?>"<?=$selected('admin_session_timeout',(string)$minutes,'60')?>><?=$minutes<60?$minutes.' minutos':($minutes/60).' hora'.($minutes>60?'s':'')?></option><?php endforeach;?></select></label><label class="integration-setting"><span><b>Alertas de login administrativo</b><small>Envia um e-mail ao administrador após um novo acesso.</small></span><input type="hidden" name="admin_login_alerts" value="0"><input type="checkbox" name="admin_login_alerts" value="1"<?=$checked('admin_login_alerts')?>><i></i></label></div></section></div><aside class="security-overview"><span class="eyebrow">DIAGNÓSTICO</span><?php foreach([['Chave da aplicação',$securityStatus['app_key']],['Segredo do webhook',$securityStatus['webhook_secret']],['Servidor SMTP',$securityStatus['smtp']],['Conexão HTTPS',$securityStatus['https']],['Debug desativado',!$securityStatus['debug']]] as [$label,$ok]):?><div><span class="security-state <?=$ok?'is-ok':'is-warning'?>"><?=$ok?'✓':'!'?></span><b><?=e($label)?></b><small><?=$ok?'Configuração adequada':'Requer atenção antes da produção'?></small></div><?php endforeach;?><p>Ambiente detectado: <strong><?=e($securityStatus['environment'])?></strong></p></aside></div>
        <?php endif;?>

        <footer class="platform-settings__savebar" data-settings-savebar hidden><span><i></i> Alterações não salvas</span><button class="button button--secondary" type="button" data-settings-discard>Descartar</button><button class="button button--primary" data-settings-submit>Salvar alterações</button></footer>
    </form>
</div>
