<?php $shippingTotal=(float)($shipping['shipping_total']??0);$grandTotal=max(0,(float)$cart['total']+$shippingTotal);$initialAddress=$addresses[0]??null; ?>
<div class="checkout-progress"><div class="container"><span class="is-complete"><i>✓</i><b>Carrinho</b></span><em></em><span class="is-current"><i>2</i><b>Entrega e pagamento</b></span><em></em><span><i>3</i><b>Confirmação</b></span></div></div>
<nav class="commerce-breadcrumb checkout-container container"><a href="<?=e(url('/carrinho'))?>">← Voltar ao carrinho</a></nav>
<section class="checkout-heading checkout-container container"><span class="eyebrow">FINALIZAR COMPRA</span><h1>Checkout seguro</h1><p>Conclua uma etapa por vez e revise tudo antes do pagamento.</p></section>
<form class="checkout-layout checkout-container container" action="<?=e(url('/checkout/finalizar'))?>" method="post" data-checkout data-quotes-url="<?=e(url('/checkout/cotacoes'))?>" data-payment-configured="<?=$paymentConfigured?'1':'0'?>" data-customer="<?=$isCustomer?'1':'0'?>"><?=csrf_field()?>
<div class="checkout-steps">
<section class="checkout-card is-complete" data-checkout-step="identity"><button class="checkout-card__header" type="button" data-step-toggle><span>✓</span><div><h2>Identificação</h2><p data-step-summary><?=$isCustomer?e($authUser['name'].' · '.$authUser['email']):'Entre para continuar'?></p></div><b>Alterar</b></button><div class="checkout-card__body"><?php if($isCustomer):?><div class="identity-confirmed"><i><?=e(mb_substr($authUser['name'],0,1))?></i><div><strong><?=e($authUser['name'])?></strong><span><?=e($authUser['email'])?></span></div><a href="<?=e(url('/minha-conta/perfil'))?>">Editar meus dados</a></div><?php else:?><div class="checkout-login"><div><strong>Entre como cliente</strong><p>Seu carrinho continuará salvo.</p></div><a class="button button--dark" href="<?=e(url('/entrar'))?>">Entrar ou criar conta</a></div><?php endif;?></div></section>

<section class="checkout-card <?=$isCustomer&&$addresses?'is-complete':'is-open'?>" data-checkout-step="address"><button class="checkout-card__header" type="button" data-step-toggle><span><?=$addresses?'✓':'2'?></span><div><h2>Onde você quer receber?</h2><p data-step-summary><?=$initialAddress?e($initialAddress['street'].', '.$initialAddress['number'].' · '.$initialAddress['city'].'/'.$initialAddress['state']):'Selecione ou cadastre um endereço'?></p></div><b>Alterar</b></button><div class="checkout-card__body"><?php if($addresses):?><div class="address-options"><?php foreach($addresses as $index=>$address):?><label class="address-option"><input type="radio" name="address_id" value="<?=(int)$address['id']?>" data-postal-code="<?=e(preg_replace('/\D+/','',$address['postal_code']))?>" data-address-summary="<?=e($address['street'].', '.$address['number'].' · '.$address['city'].'/'.$address['state'])?>" <?=$index===0?'checked':''?>><span><b><?=e($address['label']?:'Endereço')?><?=$address['is_default']?' · Principal':''?></b><strong><?=e($address['recipient_name'])?></strong><small><?=e($address['street'].', '.$address['number'].($address['complement']?' · '.$address['complement']:''))?><br><?=e($address['neighborhood'].' · '.$address['city'].'/'.$address['state'])?><br>CEP <?=e($address['postal_code'])?></small><em>Selecionar</em></span></label><?php endforeach;?></div><a class="button button--secondary address-add" href="<?=e(url('/minha-conta/enderecos/novo?return=/checkout'))?>">+ Adicionar novo endereço</a><?php elseif($isCustomer):?><div class="checkout-empty"><p>Cadastre o endereço onde deseja receber.</p><a class="button button--secondary" href="<?=e(url('/minha-conta/enderecos/novo?return=/checkout'))?>">Adicionar novo endereço</a></div><?php else:?><p class="step-placeholder">Entre para escolher o endereço de entrega.</p><?php endif;?></div></section>

<section class="checkout-card <?=!$addresses?'is-locked':(!empty($shipping['stores'])?'is-complete':'is-open')?>" data-checkout-step="shipping"><button class="checkout-card__header" type="button" data-step-toggle><span>3</span><div><h2>Entrega por loja</h2><p data-step-summary><?=!empty($shipping['stores'])?'Revise as modalidades selecionadas':'Calcule após escolher o endereço'?></p></div><b>Alterar</b></button><div class="checkout-card__body shipping-groups" data-shipping-groups><?php foreach($cart['groups'] as $group):$state=$shipping['stores'][(int)$group['store_id']]??null;?><article data-shipping-store="<?=(int)$group['store_id']?>" data-store-name="<?=e($group['store_name'])?>"><header><div><strong><?=e($group['store_name'])?></strong><span><?=count($group['items'])?> <?=count($group['items'])===1?'produto':'produtos'?></span></div><small><?=e($state['message']??'Escolha uma modalidade')?></small></header><div class="shipping-options"><?php foreach($state['options']??[] as $index=>$option):?><label><input type="radio" name="shipping[<?=(int)$group['store_id']?>]" value="<?=e($option['id'])?>" data-shipping-price="<?=e((string)$option['price'])?>" <?=$index===0?'checked':''?>><span><b><?=e($option['service'])?></b><small><?=e($option['carrier'])?> · chega entre <?=e($option['arrival_min'])?> e <?=e($option['arrival_max'])?></small></span><strong>R$ <?=number_format((float)$option['price'],2,',','.')?></strong></label><?php endforeach;?></div></article><?php endforeach;?><?php if(!$shippingConfigured):?><div class="integration-notice"><b>Cálculo de entrega em configuração</b><p>As opções reais aparecerão aqui quando o token do Melhor Envio estiver configurado.</p></div><?php endif;?></div></section>

<section class="checkout-card <?=!$addresses?'is-locked':'is-open'?>" data-checkout-step="payment"><button class="checkout-card__header" type="button" data-step-toggle><span>4</span><div><h2>Pagamento</h2><p data-step-summary>Escolha a forma de pagamento</p></div><b>Alterar</b></button><div class="checkout-card__body"><div class="payment-options"><label><input type="radio" name="payment_method" value="pix" checked><span class="payment-icon">PIX</span><span><b>Pix</b><small>Aprovação imediata</small></span></label><label><input type="radio" name="payment_method" value="card"><span class="payment-icon">▣</span><span><b>Cartão de crédito</b><small>Até 6x sem juros</small></span></label><label><input type="radio" name="payment_method" value="boleto"><span class="payment-icon">▤</span><span><b>Boleto bancário</b><small>Vencimento em 2 dias úteis</small></span></label></div><div class="payment-details"><div data-payment-panel="pix"><strong>Pagamento por Pix</strong><p>O QR Code será gerado após a criação segura do pedido.</p></div><div data-payment-panel="card" hidden><strong>Cartão de crédito</strong><p>Os dados do cartão serão preenchidos no ambiente seguro do provedor de pagamentos.</p></div><div data-payment-panel="boleto" hidden><strong>Boleto bancário</strong><p>O boleto será gerado com vencimento em dois dias úteis.</p></div></div><?php if(!$paymentConfigured):?><div class="integration-notice"><b>Pagamento em configuração</b><p>Configure as credenciais do Pagar.me para habilitar a cobrança. Nenhum dado financeiro será coletado antes disso.</p></div><?php endif;?></div></section>
</div>

<aside class="order-summary checkout-summary"><h2>Resumo da compra</h2><div class="checkout-summary__items"><?php foreach($cart['groups'] as $group):foreach($group['items'] as $item):?><article><div class="checkout-summary__thumb"><?php if($item['image_url']):?><img src="<?=e($item['image_url'])?>" alt=""><?php else:?><b>T</b><?php endif;?></div><div><strong><?=e($item['name'])?></strong><small><?=(int)$item['quantity']?> unidade(s) · <?=e($group['store_name'])?></small></div><span>R$ <?=number_format((float)$item['line_total'],2,',','.')?></span></article><?php endforeach;endforeach;?></div><dl><div><dt>Produtos</dt><dd>R$ <?=number_format((float)$cart['subtotal'],2,',','.')?></dd></div><div class="discount-row"><dt>Descontos</dt><dd>− R$ <?=number_format((float)$cart['discount_total'],2,',','.')?></dd></div><div><dt>Entrega</dt><dd data-summary-shipping><?=$shippingTotal>0?'R$ '.number_format($shippingTotal,2,',','.'):'Selecionar'?></dd></div></dl><div class="order-summary__total"><span>Total</span><strong data-summary-total data-base-total="<?=e((string)$cart['total'])?>">R$ <?=number_format($grandTotal,2,',','.')?></strong><small data-installment>ou 3x de R$ <?=number_format($grandTotal/3,2,',','.')?> sem juros</small></div><label class="checkout-terms"><input type="checkbox" name="terms" value="1" required> <span>Li e aceito os <a href="<?=e(url('/termos-de-compra'))?>" target="_blank">Termos de Compra</a> e a <a href="<?=e(url('/politica-de-privacidade'))?>" target="_blank">Política de Privacidade</a>.</span></label><button class="button button--secondary button--block checkout-submit" type="submit" disabled data-checkout-submit>Preencha o endereço e selecione a entrega</button><div class="checkout-security"><span>✓ Compra segura</span><span>✓ Pagamento protegido</span></div><small class="checkout-disclaimer">O pedido será criado como aguardando pagamento e você continuará no ambiente seguro da Pagar.me.</small></aside>
</form>
<div class="mobile-checkout-action"><span><small>Total</small><strong data-mobile-total>R$ <?=number_format($grandTotal,2,',','.')?></strong></span><button class="button button--secondary" type="button" data-mobile-submit>Continuar</button></div>
