CREATE TABLE financial_reconciliation_issues (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    settlement_id BIGINT UNSIGNED NULL,
    order_id BIGINT UNSIGNED NULL,
    payment_id BIGINT UNSIGNED NULL,
    external_charge_id VARCHAR(191) NULL,
    issue_type VARCHAR(80) NOT NULL,
    expected_value VARCHAR(255) NULL,
    actual_value VARCHAR(255) NULL,
    status ENUM('open','resolved','ignored') NOT NULL DEFAULT 'open',
    severity ENUM('info','warning','critical') NOT NULL DEFAULT 'warning',
    fingerprint CHAR(64) NOT NULL,
    detected_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at DATETIME NULL,
    resolved_by BIGINT UNSIGNED NULL,
    resolution_notes VARCHAR(1000) NULL,
    metadata JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_financial_issue_settlement FOREIGN KEY (settlement_id) REFERENCES financial_settlements(id) ON DELETE SET NULL,
    CONSTRAINT fk_financial_issue_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
    CONSTRAINT fk_financial_issue_payment FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE SET NULL,
    CONSTRAINT fk_financial_issue_resolver FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE KEY uk_financial_issue_fingerprint (fingerprint),
    INDEX idx_financial_issue_blocking (status,severity,detected_at),
    INDEX idx_financial_issue_payment (payment_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
