ALTER TABLE user_addresses
    ADD COLUMN city_ibge_code CHAR(7) NULL AFTER city;

ALTER TABLE order_addresses
    ADD COLUMN city_ibge_code CHAR(7) NULL AFTER city;

CREATE TABLE seller_fiscal_profiles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    seller_id BIGINT UNSIGNED NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    tax_regime VARCHAR(80) NULL,
    crt VARCHAR(4) NULL,
    state_registration_indicator ENUM('contributor','exempt','non_contributor') NOT NULL DEFAULT 'contributor',
    municipal_registration VARCHAR(40) NULL,
    fiscal_email VARCHAR(190) NULL,
    postal_code VARCHAR(12) NULL,
    street VARCHAR(190) NULL,
    number VARCHAR(30) NULL,
    complement VARCHAR(120) NULL,
    neighborhood VARCHAR(120) NULL,
    city VARCHAR(120) NULL,
    state CHAR(2) NULL,
    city_ibge_code CHAR(7) NULL,
    nfe_series SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    provider_settings JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_seller_fiscal_profiles_seller FOREIGN KEY (seller_id) REFERENCES sellers(id) ON DELETE CASCADE,
    UNIQUE KEY uk_seller_fiscal_profiles_seller (seller_id),
    INDEX idx_seller_fiscal_profiles_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE product_fiscal_profiles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    product_id BIGINT UNSIGNED NOT NULL,
    ncm CHAR(8) NULL,
    cest CHAR(7) NULL,
    origin TINYINT UNSIGNED NULL,
    commercial_unit VARCHAR(6) NOT NULL DEFAULT 'UN',
    tributary_unit VARCHAR(6) NOT NULL DEFAULT 'UN',
    gtin VARCHAR(20) NULL,
    cfop_in_state CHAR(4) NULL,
    cfop_out_state CHAR(4) NULL,
    icms_code VARCHAR(4) NULL,
    pis_code VARCHAR(4) NULL,
    cofins_code VARCHAR(4) NULL,
    ipi_code VARCHAR(4) NULL,
    ibs_cbs_cst VARCHAR(4) NULL,
    ibs_cbs_classification VARCHAR(20) NULL,
    tax_metadata JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_fiscal_profiles_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    UNIQUE KEY uk_product_fiscal_profiles_product (product_id),
    INDEX idx_product_fiscal_profiles_ncm (ncm)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE fiscal_documents (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    seller_order_id BIGINT UNSIGNED NOT NULL,
    seller_id BIGINT UNSIGNED NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL,
    document_type VARCHAR(20) NOT NULL DEFAULT 'nfe',
    operation_type VARCHAR(30) NOT NULL DEFAULT 'sale',
    revision SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    provider VARCHAR(60) NOT NULL DEFAULT 'disabled',
    environment VARCHAR(20) NOT NULL DEFAULT 'homologation',
    provider_document_id VARCHAR(150) NULL,
    idempotency_key VARCHAR(191) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    number BIGINT UNSIGNED NULL,
    series SMALLINT UNSIGNED NULL,
    access_key VARCHAR(60) NULL,
    protocol VARCHAR(100) NULL,
    products_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    shipping_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    discount_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    grand_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    issuer_snapshot JSON NULL,
    recipient_snapshot JSON NULL,
    tax_context JSON NULL,
    xml_storage_path TEXT NULL,
    danfe_storage_path TEXT NULL,
    validation_errors JSON NULL,
    error_code VARCHAR(100) NULL,
    error_message VARCHAR(1000) NULL,
    requires_action BOOLEAN NOT NULL DEFAULT FALSE,
    action_reason VARCHAR(1000) NULL,
    authorized_at DATETIME NULL,
    cancelled_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_fiscal_documents_seller_order FOREIGN KEY (seller_order_id) REFERENCES seller_orders(id),
    CONSTRAINT fk_fiscal_documents_seller FOREIGN KEY (seller_id) REFERENCES sellers(id),
    CONSTRAINT fk_fiscal_documents_store FOREIGN KEY (store_id) REFERENCES stores(id),
    UNIQUE KEY uk_fiscal_documents_revision (seller_order_id, document_type, revision),
    UNIQUE KEY uk_fiscal_documents_idempotency (idempotency_key),
    UNIQUE KEY uk_fiscal_documents_access_key (access_key),
    INDEX idx_fiscal_documents_status_created (status, created_at),
    INDEX idx_fiscal_documents_seller_status (seller_id, status),
    INDEX idx_fiscal_documents_store_status (store_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE fiscal_document_items (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    fiscal_document_id BIGINT UNSIGNED NOT NULL,
    order_item_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,
    product_variant_id BIGINT UNSIGNED NOT NULL,
    product_name VARCHAR(190) NOT NULL,
    sku VARCHAR(100) NOT NULL,
    quantity INT UNSIGNED NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL,
    total DECIMAL(12,2) NOT NULL,
    ncm CHAR(8) NULL,
    cest CHAR(7) NULL,
    origin TINYINT UNSIGNED NULL,
    commercial_unit VARCHAR(6) NULL,
    tributary_unit VARCHAR(6) NULL,
    gtin VARCHAR(20) NULL,
    cfop_in_state CHAR(4) NULL,
    cfop_out_state CHAR(4) NULL,
    applied_cfop CHAR(4) NULL,
    icms_code VARCHAR(4) NULL,
    pis_code VARCHAR(4) NULL,
    cofins_code VARCHAR(4) NULL,
    ipi_code VARCHAR(4) NULL,
    ibs_cbs_cst VARCHAR(4) NULL,
    ibs_cbs_classification VARCHAR(20) NULL,
    tax_metadata JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_fiscal_document_items_document FOREIGN KEY (fiscal_document_id) REFERENCES fiscal_documents(id) ON DELETE CASCADE,
    CONSTRAINT fk_fiscal_document_items_order_item FOREIGN KEY (order_item_id) REFERENCES order_items(id),
    CONSTRAINT fk_fiscal_document_items_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_fiscal_document_items_variant FOREIGN KEY (product_variant_id) REFERENCES product_variants(id),
    UNIQUE KEY uk_fiscal_document_items_order_item (fiscal_document_id, order_item_id),
    INDEX idx_fiscal_document_items_document (fiscal_document_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE fiscal_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    fiscal_document_id BIGINT UNSIGNED NOT NULL,
    event_type VARCHAR(60) NOT NULL,
    status VARCHAR(30) NOT NULL,
    provider_event_id VARCHAR(150) NULL,
    code VARCHAR(100) NULL,
    message VARCHAR(1000) NULL,
    payload_sha256 CHAR(64) NULL,
    occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fiscal_events_document FOREIGN KEY (fiscal_document_id) REFERENCES fiscal_documents(id) ON DELETE CASCADE,
    INDEX idx_fiscal_events_document_created (fiscal_document_id, created_at),
    INDEX idx_fiscal_events_provider_event (provider_event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
