CREATE TABLE store_fiscal_profiles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    store_id BIGINT UNSIGNED NOT NULL,
    seller_id BIGINT UNSIGNED NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    issuance_mode ENUM('platform','manual','external') NOT NULL DEFAULT 'manual',
    provider VARCHAR(60) NOT NULL DEFAULT 'disabled',
    environment ENUM('homologation','production') NOT NULL DEFAULT 'homologation',
    auto_issue BOOLEAN NOT NULL DEFAULT FALSE,
    legal_name VARCHAR(190) NULL,
    trade_name VARCHAR(190) NULL,
    document VARCHAR(40) NULL,
    state_registration VARCHAR(40) NULL,
    tax_regime VARCHAR(80) NULL,
    crt VARCHAR(4) NULL,
    state_registration_indicator ENUM('contributor','exempt','non_contributor') NOT NULL DEFAULT 'contributor',
    municipal_registration VARCHAR(40) NULL,
    fiscal_email VARCHAR(190) NULL,
    postal_code VARCHAR(12) NULL,
    street VARCHAR(190) NULL,
    number VARCHAR(30) NULL,
    complement VARCHAR(120) NULL,
    neighborhood VARCHAR(120) NULL,
    city VARCHAR(120) NULL,
    state CHAR(2) NULL,
    city_ibge_code CHAR(7) NULL,
    nfe_series SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    provider_settings JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_store_fiscal_profiles_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
    CONSTRAINT fk_store_fiscal_profiles_seller FOREIGN KEY (seller_id) REFERENCES sellers(id) ON DELETE CASCADE,
    UNIQUE KEY uk_store_fiscal_profiles_store (store_id),
    INDEX idx_store_fiscal_profiles_seller (seller_id),
    INDEX idx_store_fiscal_profiles_mode_enabled (issuance_mode, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE fiscal_documents
    ADD COLUMN issuance_mode VARCHAR(20) NOT NULL DEFAULT 'platform' AFTER operation_type;
