CREATE TABLE shipment_label_replacements (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    shipment_id BIGINT UNSIGNED NOT NULL,
    seller_order_id BIGINT UNSIGNED NOT NULL,
    order_id BIGINT UNSIGNED NOT NULL,
    changed_by BIGINT UNSIGNED NULL,
    reason VARCHAR(500) NULL,
    old_service_id VARCHAR(80) NULL,
    old_service_name VARCHAR(150) NULL,
    old_carrier_name VARCHAR(150) NULL,
    old_external_id VARCHAR(120) NULL,
    old_tracking_code VARCHAR(120) NULL,
    old_label_url TEXT NULL,
    old_label_actual_cost DECIMAL(12,2) NULL,
    old_label_purchase_status VARCHAR(40) NULL,
    remote_cancelled_at DATETIME NULL,
    new_service_id VARCHAR(80) NOT NULL,
    new_service_name VARCHAR(150) NOT NULL,
    new_carrier_name VARCHAR(150) NOT NULL,
    new_expected_cost DECIMAL(12,2) NOT NULL,
    new_external_id VARCHAR(120) NULL,
    new_tracking_code VARCHAR(120) NULL,
    new_label_url TEXT NULL,
    new_label_actual_cost DECIMAL(12,2) NULL,
    new_label_purchase_status VARCHAR(40) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_label_replacement_shipment FOREIGN KEY (shipment_id) REFERENCES shipments(id) ON DELETE RESTRICT,
    CONSTRAINT fk_label_replacement_seller_order FOREIGN KEY (seller_order_id) REFERENCES seller_orders(id) ON DELETE RESTRICT,
    CONSTRAINT fk_label_replacement_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
    CONSTRAINT fk_label_replacement_admin FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_label_replacements_shipment (shipment_id,created_at),
    INDEX idx_label_replacements_order (order_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
