<div class="dashboard-heading"><div><span class="eyebrow">CADASTRO EMPRESARIAL</span><h2>Conte sobre a sua empresa.</h2><p>O CNPJ identifica o perfil atacadista e não altera seu cadastro pessoal.</p></div></div>
<?php require __DIR__ . '/_steps.php'; ?>
<form class="panel resource-form wholesale-form" method="post" action="<?= e(url('/minha-conta/atacado/empresa')) ?>"><?= csrf_field() ?>
<div class="form-section-head"><span>01</span><div><h3>Dados da empresa</h3><p>Campos com * são obrigatórios.</p></div></div><div class="form-grid">
<label>CNPJ *<input name="cnpj" data-mask="cnpj" required inputmode="numeric" value="<?= e(old('cnpj', $account['cnpj'] ?? '')) ?>" placeholder="00.000.000/0000-00"><?php if(error('cnpj')):?><small class="field-error"><?=e(error('cnpj'))?></small><?php endif;?></label>
<label>Razão social *<input name="legal_name" required value="<?= e(old('legal_name', $account['legal_name'] ?? '')) ?>"><?php if(error('legal_name')):?><small class="field-error"><?=e(error('legal_name'))?></small><?php endif;?></label>
<label>Nome fantasia *<input name="trade_name" required value="<?= e(old('trade_name', $account['trade_name'] ?? '')) ?>"><?php if(error('trade_name')):?><small class="field-error"><?=e(error('trade_name'))?></small><?php endif;?></label>
<label>Data de abertura<input type="date" name="opened_at" value="<?= e(old('opened_at', $account['opened_at'] ?? '')) ?>"></label>
<label>Situação da inscrição estadual *<select name="state_registration_status" required data-ie-status><option value="">Selecione</option><?php foreach(['taxpayer'=>'Contribuinte','exempt'=>'Isento','non_taxpayer'=>'Não contribuinte'] as $value=>$label):?><option value="<?=e($value)?>" <?= old('state_registration_status',$account['state_registration_status']??'')===$value?'selected':'' ?>><?=e($label)?></option><?php endforeach;?></select><?php if(error('state_registration_status')):?><small class="field-error"><?=e(error('state_registration_status'))?></small><?php endif;?></label>
<label data-ie-field>Inscrição estadual<input name="state_registration" value="<?= e(old('state_registration', $account['state_registration'] ?? '')) ?>"><?php if(error('state_registration')):?><small class="field-error"><?=e(error('state_registration'))?></small><?php endif;?></label>
<label>Telefone comercial<input name="business_phone" data-mask="phone" value="<?= e(old('business_phone', $account['business_phone'] ?? '')) ?>"></label>
<label>E-mail comercial<input type="email" name="business_email" value="<?= e(old('business_email', $account['business_email'] ?? '')) ?>"><?php if(error('business_email')):?><small class="field-error"><?=e(error('business_email'))?></small><?php endif;?></label>
<label>Site<input type="url" name="website" value="<?= e(old('website', $account['website'] ?? '')) ?>" placeholder="https://"></label>
<label>Segmento<select name="business_segment"><option value="">Selecione</option><?php foreach(['Loja de roupas','Loja de roupas íntimas','Revendedor','Distribuidor','Marketplace','Loja física','Loja virtual','Outro'] as $segment):?><option <?= old('business_segment',$account['business_segment']??'')===$segment?'selected':'' ?>><?=e($segment)?></option><?php endforeach;?></select></label>
<label>Volume médio mensal (unidades)<input type="number" min="0" name="average_monthly_volume" value="<?= e(old('average_monthly_volume', $account['average_monthly_volume'] ?? '')) ?>"></label>
</div><div class="form-actions"><a class="button button--secondary" href="<?=e(url('/minha-conta/atacado'))?>">Voltar</a><button class="button button--primary">Continuar</button></div></form>
