<?php
$qualityLabel = $product['quality_score'] >= 85 ? 'Excelente' : ($product['quality_score'] >= 65 ? 'Bom' : ($product['quality_score'] >= 40 ? 'Incompleto' : 'Crítico'));
$moderationLabels = ['pending'=>'Pendente de análise','under_review'=>'Em análise','approved'=>'Aprovado','changes_requested'=>'Correção solicitada','rejected'=>'Rejeitado'];
$actionLabels = ['analysis_started'=>'Análise iniciada','approved'=>'Anúncio aprovado','changes_requested'=>'Correções solicitadas','rejected'=>'Anúncio rejeitado','platform_paused'=>'Pausado pela plataforma','platform_resumed'=>'Pausa removida','featured'=>'Produto destacado','unfeatured'=>'Destaque removido'];
$checks = [
    ['Nome', mb_strlen(trim((string)$product['product_name'])) >= 20, 'Use um título claro com pelo menos 20 caracteres.'],
    ['Descrição', mb_strlen(trim((string)$product['description'])) >= 120, 'A descrição precisa explicar melhor o produto.'],
    ['Categoria', !empty($product['primary_category_id']), 'Defina a categoria principal.'],
    ['Preço', (float)$product['price'] > 0, 'O vendedor precisa configurar um preço válido.'],
    ['Estoque', (int)$product['stock'] > 0 || !empty($product['allow_backorder']), 'Produto sem estoque disponível.'],
    ['Dimensões', !empty($product['has_dimensions']), 'Peso ou dimensões estão incompletos.'],
    ['Imagens', (int)$product['image_count'] >= 3, (int)$product['image_count'] ? 'Recomendamos pelo menos 3 imagens.' : 'O anúncio não possui imagens.'],
    ['Vídeo', (int)$product['video_count'] > 0, 'Vídeo opcional não informado.'],
    ['Especificações', (int)$product['specification_count'] > 0, 'Adicione especificações técnicas.'],
    ['Variações', (int)$product['variant_count'] > 0, 'Nenhuma variação comercial configurada.'],
];
?>

<div class="product-review-header">
    <div><a class="back-link" href="<?= e(url('/admin/produtos')) ?>">← Voltar ao catálogo global</a><span class="eyebrow">REVISÃO DO ANÚNCIO #<?= (int)$product['product_id'] ?></span><h2><?= e($product['product_name']) ?></h2><p>Loja: <a href="<?= e(url('/admin/lojas/'.$product['store_id'].'/editar')) ?>"><?= e($product['store_name']) ?></a> · Atualizado em <?= date('d/m/Y \à\s H:i',strtotime($product['updated_at'])) ?></p></div>
    <div class="product-review-header__status"><span class="moderation-status moderation-status--<?= e($product['moderation_status']) ?>"><?= e($moderationLabels[$product['moderation_status']]??$product['moderation_status']) ?></span><span class="quality-score"><strong><?= (int)$product['quality_score'] ?>%</strong><span><?= e($qualityLabel) ?></span></span></div>
</div>

<div class="product-review-actions">
    <?php if($product['commercial_status']==='active'&&!$product['platform_paused']):?><a class="button button--secondary" href="<?= e(url('/produto/'.$product['product_slug'])) ?>" target="_blank" rel="noopener">Visualizar na loja</a><?php endif;?>
    <a class="button button--secondary" href="<?= e(url('/admin/lojas/'.$product['store_id'].'/editar')) ?>">Acessar loja</a>
    <?php if(!empty($permissions['catalog.review'])&&$product['moderation_status']!=='under_review'):?><form method="post" action="<?= e(url('/admin/produtos/'.$product['product_id'].'/iniciar-analise')) ?>"><?= csrf_field() ?><button class="button button--secondary">Iniciar análise</button></form><?php endif;?>
</div>

<nav class="review-tabs"><a href="#visao-geral">Visão geral</a><a href="#qualidade">Qualidade</a><a href="#variacoes">Preços e estoque</a><a href="#midias">Mídias</a><a href="#moderacao">Moderação</a><a href="#historico">Histórico</a><a href="#denuncias">Denúncias</a></nav>

<div class="catalog-review-layout">
    <main class="catalog-review-main">
        <section class="panel review-card" id="visao-geral"><header><div><span>VISÃO GERAL</span><h3>Informações do anúncio</h3></div><span class="sale-chip"><?= $product['retail_enabled']&&$product['wholesale_enabled']?'Varejo e atacado':($product['wholesale_enabled']?'Atacado':'Varejo') ?></span></header><dl class="review-detail-grid"><div><dt>SKU</dt><dd><?= e($product['product_sku']?:'Não informado') ?></dd></div><div><dt>Marca</dt><dd><?= e($product['brand_name']?:'Não informada') ?></dd></div><div><dt>Categoria principal</dt><dd><?= e($product['category_name']?:'Não informada') ?></dd></div><div><dt>Tipo</dt><dd><?= e(ucfirst($product['product_type'])) ?></dd></div><div><dt>Status da loja</dt><dd><?= e(ucfirst($product['commercial_status'])) ?></dd></div><div><dt>Disponibilidade</dt><dd><?= $product['platform_paused']?'Pausado pela plataforma':'Sem bloqueio administrativo' ?></dd></div></dl><?php if($categories):?><div class="review-tag-list"><strong>Categorias adicionais</strong><?php foreach($categories as $category):?><span><?= e($category['name']) ?></span><?php endforeach;?></div><?php endif;?><?php if($tags):?><div class="review-tag-list"><strong>Tags</strong><?php foreach($tags as $tag):?><span><?= e($tag['name']) ?></span><?php endforeach;?></div><?php endif;?><div class="review-description"><strong>Descrição</strong><p><?= nl2br(e($product['description']?:'Descrição não informada.')) ?></p></div></section>

        <section class="panel review-card" id="qualidade"><header><div><span>QUALIDADE DO ANÚNCIO</span><h3><?= (int)$product['quality_score'] ?>% · <?= e($qualityLabel) ?></h3></div><span><?= (int)$product['alert_count'] ?> alerta(s)</span></header><div class="quality-checklist"><?php foreach($checks as [$label,$passed,$help]):?><div class="<?= $passed?'is-passed':'is-warning' ?>"><span><?= $passed?'✓':'!' ?></span><div><strong><?= e($label) ?></strong><small><?= $passed?'Critério atendido.':e($help) ?></small></div></div><?php endforeach;?></div><?php if((int)$product['low_resolution_images']>0):?><p class="review-warning">⚠ <?= (int)$product['low_resolution_images'] ?> imagem(ns) abaixo de 1080 × 1080 pixels.</p><?php endif;?></section>

        <section class="panel review-card" id="variacoes"><header><div><span>DADOS DO VENDEDOR · SOMENTE CONSULTA</span><h3>Preços, variações e estoque</h3></div><small>O administrador não altera estes dados.</small></header><div class="table-wrap"><table><thead><tr><th>Variação</th><th>SKU / EAN</th><th>Preço</th><th>Atacado</th><th>Estoque</th><th>Status</th></tr></thead><tbody><?php foreach($variants as $variant):?><tr><td><?= e($variant['name']?:'Padrão') ?></td><td><strong><?= e($variant['sku']) ?></strong><small><?= e($variant['barcode']?:'Sem EAN') ?></small></td><td>R$ <?= number_format((float)($variant['promotional_price']?:$variant['price']),2,',','.') ?></td><td><?= $variant['wholesale_price']!==null?'R$ '.number_format((float)$variant['wholesale_price'],2,',','.'):'—' ?></td><td><?= (int)$variant['stock'] ?></td><td><?= e($variant['status']) ?></td></tr><?php endforeach;?></tbody></table></div></section>

        <section class="panel review-card" id="midias"><header><div><span>MÍDIAS</span><h3>Imagens e vídeos</h3></div><span><?= count($media) ?> arquivo(s)</span></header><div class="review-media-grid"><?php foreach($media as $item):?><a href="<?= e($item['secure_url']) ?>" target="_blank" rel="noopener"><?php if($item['resource_type']==='image'):?><img src="<?= e($item['thumbnail_url']?:$item['secure_url']) ?>" alt="" loading="lazy"><?php else:?><span>▶ Vídeo</span><?php endif;?><small><?= (int)$item['width'] ?> × <?= (int)$item['height'] ?><?= $item['is_cover']?' · Capa':'' ?></small></a><?php endforeach;?><?php if(!$media):?><p>Nenhuma mídia cadastrada.</p><?php endif;?></div></section>

        <section class="panel review-card" id="historico"><header><div><span>AUDITORIA</span><h3>Histórico de moderação</h3></div></header><div class="moderation-timeline"><?php foreach($history as $event):?><article><i></i><div><strong><?= e($actionLabels[$event['action']]??ucfirst(str_replace('_',' ',$event['action']))) ?></strong><p><?= e($event['reason']?:'Sem observações adicionais.') ?></p><small>Alterado por: <?= e($event['admin_name']?:'Administrador Tuffer') ?> · <?= date('d/m/Y \à\s H:i',strtotime($event['created_at'])) ?></small></div></article><?php endforeach;?><?php if(!$history):?><p>Nenhuma ação administrativa registrada.</p><?php endif;?></div></section>

        <section class="panel review-card" id="denuncias"><header><div><span>SEGURANÇA</span><h3>Denúncias e reclamações</h3></div><span><?= count($reports) ?></span></header><?php foreach($reports as $report):?><article class="report-item"><div><strong><?= e($report['reason']) ?></strong><span class="moderation-status moderation-status--<?= e($report['status']) ?>"><?= e($report['status']) ?></span></div><p><?= e($report['description']?:'Sem detalhes adicionais.') ?></p><small><?= e($report['reporter_name']?:'Relato anônimo') ?> · <?= date('d/m/Y H:i',strtotime($report['created_at'])) ?></small></article><?php endforeach;?><?php if(!$reports):?><p>Este produto não possui denúncias.</p><?php endif;?></section>
    </main>

    <aside class="panel moderation-panel" id="moderacao"><span class="eyebrow">MODERAÇÃO</span><h3>Decisão sobre o anúncio</h3><p>As ações abaixo não transferem a propriedade do produto nem alteram preço ou estoque.</p>
        <?php if(!empty($permissions['catalog.approve'])):?><form method="post" action="<?= e(url('/admin/produtos/'.$product['product_id'].'/aprovar')) ?>"><?= csrf_field() ?><button class="button button--primary">Aprovar anúncio</button></form><?php endif;?>
        <?php if(!empty($permissions['catalog.request_changes'])||!empty($permissions['catalog.reject'])||(!empty($permissions['catalog.pause'])&&!$product['platform_paused'])):?><form class="moderation-reason-form" method="post"><?= csrf_field() ?><label>Motivo e orientação ao vendedor<textarea name="reason" required minlength="10" placeholder="Explique o problema encontrado e como corrigi-lo..."><?= e($product['moderation_reason']??'') ?></textarea></label><?php if(!empty($permissions['catalog.request_changes'])):?><button class="button button--secondary" formaction="<?= e(url('/admin/produtos/'.$product['product_id'].'/solicitar-correcoes')) ?>">Solicitar correções</button><?php endif;?><?php if(!empty($permissions['catalog.pause'])&&!$product['platform_paused']):?><button class="button button--secondary" formaction="<?= e(url('/admin/produtos/'.$product['product_id'].'/pausar')) ?>">Pausar pela plataforma</button><?php endif;?><?php if(!empty($permissions['catalog.reject'])):?><button class="button button--danger" formaction="<?= e(url('/admin/produtos/'.$product['product_id'].'/rejeitar')) ?>" onclick="return confirm('Rejeitar este anúncio?')">Rejeitar anúncio</button><?php endif;?></form><?php endif;?>
        <?php if(!empty($permissions['catalog.pause'])&&$product['platform_paused']):?><form method="post" action="<?= e(url('/admin/produtos/'.$product['product_id'].'/retomar')) ?>"><?= csrf_field() ?><button class="button button--primary">Remover pausa administrativa</button></form><?php endif;?>
        <?php if(!empty($permissions['catalog.feature'])):?><form class="feature-form" method="post" action="<?= e(url('/admin/produtos/'.$product['product_id'].'/destaque')) ?>"><?= csrf_field() ?><input type="hidden" name="featured" value="<?= $product['featured']?'0':'1' ?>"><button class="button button--secondary"><?= $product['featured']?'Remover destaque':'Destacar em campanhas' ?></button></form><?php endif;?>
        <?php if($product['moderation_reason']):?><div class="current-moderation-note"><strong>Motivo atual</strong><p><?= e($product['moderation_reason']) ?></p></div><?php endif;?>
    </aside>
</div>
