<?php

declare(strict_types=1);

use App\Core\Database;use App\Core\Logger;use App\Services\Monitoring\AlertService;use Dotenv\Dotenv;

$root=dirname(__DIR__);require $root.'/vendor/autoload.php';Dotenv::createImmutable($root)->safeLoad();date_default_timezone_set('America/Sao_Paulo');Logger::register();$pdo=Database::connection();$alerts=new AlertService();$checks=[];
$record=static function(string $service,string $status,?int $milliseconds,array $details=[])use($pdo,&$checks):void{$pdo->prepare('INSERT INTO service_health_checks(service,status,response_time_ms,details) VALUES(?,?,?,?)')->execute([$service,$status,$milliseconds,json_encode($details,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);$checks[$service]=$status;};

try{$start=microtime(true);$pdo->query('SELECT 1');$record('database','ok',(int)round((microtime(true)-$start)*1000));$alerts->resolve('database','Banco de dados indisponível.');}catch(Throwable $exception){$record('database','down',null,['error'=>$exception->getMessage()]);$alerts->raise('database','Banco de dados indisponível.','critical');}
$storage=$root.'/storage';$writable=is_dir($storage)&&is_writable($storage);$free=@disk_free_space($storage);$total=@disk_total_space($storage);$freePercent=$free!==false&&$total?round(($free/$total)*100,2):null;$storageStatus=!$writable||($freePercent!==null&&$freePercent<5)?'down':(($freePercent!==null&&$freePercent<15)?'degraded':'ok');$record('storage',$storageStatus,null,['free_percent'=>$freePercent,'writable'=>$writable]);if($storageStatus!=='ok')$alerts->raise('storage','Armazenamento com pouca capacidade ou sem permissão de escrita.',$storageStatus==='down'?'critical':'warning');else $alerts->resolve('storage','Armazenamento com pouca capacidade ou sem permissão de escrita.');
$backup=$pdo->query("SELECT completed_at FROM backup_runs WHERE status='completed' ORDER BY completed_at DESC LIMIT 1")->fetchColumn();$maximumAge=max(1,(int)($_ENV['BACKUP_MAX_AGE_HOURS']??26));$backupAge=$backup?(time()-strtotime((string)$backup))/3600:null;$backupStatus=$backupAge!==null&&$backupAge<=$maximumAge?'ok':'degraded';$record('backup',$backupStatus,null,['last_completed_at'=>$backup?:null,'age_hours'=>$backupAge]);if($backupStatus!=='ok')$alerts->raise('database_backup','Nenhum backup recente do banco foi encontrado.','warning');else $alerts->resolve('database_backup','Nenhum backup recente do banco foi encontrado.');
$host=(string)($_ENV['MAIL_HOST']??'');$port=(int)($_ENV['MAIL_PORT']??587);$start=microtime(true);$socket=$host!==''?@stream_socket_client('tcp://'.$host.':'.$port,$number,$error,5):false;$smtpStatus=is_resource($socket)?'ok':'down';if(is_resource($socket))fclose($socket);$record('smtp',$smtpStatus,(int)round((microtime(true)-$start)*1000));if($smtpStatus==='down')$alerts->raise('smtp','Servidor SMTP indisponível.','critical');else $alerts->resolve('smtp','Servidor SMTP indisponível.');
$queue=$pdo->query("SELECT SUM(status='failed') failed_jobs,SUM(status='processing' AND reserved_at<DATE_SUB(NOW(),INTERVAL 15 MINUTE)) stuck_jobs,SUM(status='pending' AND available_at<DATE_SUB(NOW(),INTERVAL 10 MINUTE)) delayed_jobs FROM async_jobs")->fetch();$queueStatus=(int)$queue['failed_jobs']>0||(int)$queue['stuck_jobs']>0||(int)$queue['delayed_jobs']>0?'degraded':'ok';$record('queue',$queueStatus,null,['failed'=>(int)$queue['failed_jobs'],'stuck'=>(int)$queue['stuck_jobs'],'delayed'=>(int)$queue['delayed_jobs']]);if($queueStatus!=='ok')$alerts->raise('async_queue','A fila possui jobs falhos, travados ou atrasados.','warning');else $alerts->resolve('async_queue','A fila possui jobs falhos, travados ou atrasados.');
$queueRetention=max(7,(int)($_ENV['QUEUE_RETENTION_DAYS']??30));$pdo->exec("DELETE FROM async_jobs WHERE status='completed' AND completed_at<DATE_SUB(NOW(),INTERVAL {$queueRetention} DAY)");
$overall=in_array('down',$checks,true)?'down':(in_array('degraded',$checks,true)?'degraded':'ok');$retention=max(7,(int)($_ENV['LOG_RETENTION_DAYS']??30));$pdo->exec('DELETE FROM application_logs WHERE created_at<DATE_SUB(NOW(),INTERVAL '.$retention.' DAY)');$pdo->exec('DELETE FROM service_health_checks WHERE checked_at<DATE_SUB(NOW(),INTERVAL '.$retention.' DAY)');Logger::info('Monitoramento concluído.',['status'=>$overall,'checks'=>$checks],'monitoring');echo 'MONITOR='.$overall.' '.json_encode($checks,JSON_UNESCAPED_SLASHES).PHP_EOL;exit($overall==='down'?1:0);
