<?php require __DIR__ . '/newsletter.php'; ?>
<footer class="site-footer">
    <div class="container footer-grid">
        <div class="footer-about"><a class="brand footer-logo" href="<?= e(url('/')) ?>" aria-label="<?= e($platformSettings['platform_name'] ?? 'Tuffer') ?>, página inicial"><img src="<?= e(upload_asset(!empty($platformSettings['logo_dark_path']) ? $platformSettings['logo_dark_path'] : 'platform/logos/tuffer-logo-white.svg')) ?>" alt="<?= e($platformSettings['platform_name'] ?? 'Tuffer') ?>"></a><p><?= e($platformSettings['tagline'] ?? 'Marketplace com produtos de lojas oficiais, checkout centralizado, ofertas e novidades em uma experiência simples de compra.') ?></p><a class="footer-policy-hub" href="<?= e(url('/politicas')) ?>">Central de Políticas →</a></div>
        <div><strong>Para compradores</strong><a href="<?= e(url('/produtos')) ?>">Como comprar</a><a href="<?= e(url('/politicas/pagamentos-reembolsos')) ?>">Pagamentos e reembolsos</a><a href="<?= e(url('/politicas/entrega-frete')) ?>">Entrega e frete</a><a href="<?= e(url('/politicas/trocas-devolucoes-arrependimento')) ?>">Trocas e devoluções</a><a href="<?= e(url('/politicas/atendimento-reclamacoes-disputas')) ?>">Atendimento e reclamações</a><a href="<?= e(url('/politicas/seguranca-informacao')) ?>">Segurança</a></div>
        <div><strong>Para vendedores</strong><a href="<?= e(url('/quero-vender')) ?>">Venda na Tuffer</a><a href="<?= e(url('/politicas/termos-vendedores')) ?>">Termos para vendedores</a><a href="<?= e(url('/politicas/comissoes-tarifas-recebimentos')) ?>">Comissões e recebimentos</a><a href="<?= e(url('/politicas/anuncios-cadastro-produtos')) ?>">Cadastro de produtos</a><a href="<?= e(url('/politicas/produtos-permitidos-proibidos')) ?>">Produtos permitidos</a><a href="<?= e(url('/politicas/desempenho-penalidades-vendedor')) ?>">Desempenho e penalidades</a><a href="<?= e(url('/politicas/fiscal-vendedores')) ?>">Política fiscal</a></div>
        <div><strong>Institucional e legal</strong><a href="<?= e(url('/politicas/termos-de-uso')) ?>">Termos de Uso</a><a href="<?= e(url('/politicas/privacidade')) ?>">Política de Privacidade</a><a href="<?= e(url('/politicas/cookies')) ?>">Política de Cookies</a><a href="<?= e(url('/politicas/propriedade-intelectual')) ?>">Propriedade Intelectual</a><a href="<?= e(url('/politicas/acessibilidade')) ?>">Acessibilidade</a><a href="mailto:<?= e($platformSettings['privacy_email'] ?? $platformSettings['support_email'] ?? 'contato@tuffer.com.br') ?>">Canal de Privacidade</a></div>
    </div>
    <div class="container footer-bottom"><span>© <?= date('Y') ?> <?= e($platformSettings['platform_name'] ?? 'Tuffer') ?>. Todos os direitos reservados.</span><span>Desenvolvido por <a href="https://www.instagram.com/miguelalmeida.j/" target="_blank" rel="noopener noreferrer">Miguel Almeida</a></span></div>
</footer>
