<header class="commerce-hero commerce-hero--seller">
    <div>
        <span class="eyebrow">MÓDULO FISCAL</span>
        <h2>Fiscal da loja</h2>
        <p>Cada loja escolhe como emite sua NF-e; a Tuffer mantém o vínculo com o pedido.</p>
    </div>
    <div class="seller-identity">
        <span>NF</span>
        <div><strong><?=e($currentStore['name'])?></strong><small><?=e($fiscalMode)?> · <?=e($fiscalProvider)?> · <?=e($fiscalEnvironment)?></small></div>
    </div>
</header>
<div class="settings-note"><span>!</span><p>Modo atual: <strong><?=e(str_replace('_',' ',$fiscalMode))?></strong>. <?php if($fiscalMode==='platform'):?>Emissão automática: <strong><?=$fiscalAutoIssue?'habilitada':'desabilitada'?></strong>.<?php elseif($fiscalMode==='manual'):?>A loja emite fora da Tuffer e registra a chave da NF-e aqui.<?php else:?>A Tuffer aguarda o sistema externo devolver os dados da NF-e.<?php endif;?></p></div>
<?php if(($profile['profile_source']??'')==='seller_fallback'):?><div class="settings-note"><span>i</span><p>Esta loja ainda usa a configuração fiscal antiga do vendedor como fallback. Ao salvar, será criado um perfil fiscal próprio para esta loja.</p></div><?php endif;?>
<form class="settings-form" method="post" action="<?=e(url('/vendedor/fiscal/perfil'))?>"><?=csrf_field()?>
<section class="settings-card"><header><span>01</span><div><h3>Como esta loja emite?</h3><p>O método é independente das outras lojas do mesmo vendedor.</p></div></header><div class="settings-grid">
<label class="settings-field">Módulo fiscal<select name="enabled"><option value="0" <?=empty($profile['enabled'])?'selected':''?>>Desabilitado</option><option value="1" <?=!empty($profile['enabled'])?'selected':''?>>Habilitado</option></select></label>
<label class="settings-field">Modo de emissão<select name="issuance_mode"><option value="platform" <?=$fiscalMode==='platform'?'selected':''?>>Pela Tuffer</option><option value="manual" <?=$fiscalMode==='manual'?'selected':''?>>Manual / sistema próprio</option><option value="external" <?=$fiscalMode==='external'?'selected':''?>>Integração externa / ERP</option></select></label>
<label class="settings-field">Provider / integração<select name="provider"><?php $selectedProvider=(string)$fiscalProvider;foreach(['disabled'=>'Ainda não configurado','focus'=>'Focus NFe','nuvem_fiscal'=>'Nuvem Fiscal','plugnotas'=>'PlugNotas','external'=>'ERP/API externa','custom'=>'Provider personalizado'] as $value=>$label):?><option value="<?=e($value)?>" <?=$selectedProvider===$value?'selected':''?>><?=e($label)?></option><?php endforeach;?></select><small>No modo manual o provider é registrado como <code>manual</code>.</small></label>
<label class="settings-field">Ambiente<select name="environment"><option value="homologation" <?=$fiscalEnvironment==='homologation'?'selected':''?>>Homologação</option><option value="production" <?=$fiscalEnvironment==='production'?'selected':''?>>Produção</option></select></label>
<label class="settings-field">Emissão automática pela Tuffer<select name="auto_issue"><option value="0" <?=!$fiscalAutoIssue?'selected':''?>>Não</option><option value="1" <?=$fiscalAutoIssue?'selected':''?>>Sim</option></select><small>Só é usada no modo “Pela Tuffer”.</small></label>
</div></section>
<section class="settings-card"><header><span>02</span><div><h3>Emissor desta loja</h3><p>Permite CNPJ, IE, série e endereço fiscal diferentes por estabelecimento.</p></div></header><div class="settings-grid">
<label class="settings-field">Razão social<input name="legal_name" required value="<?=e($profile['legal_name']??$seller['legal_name']??'')?>"></label><label class="settings-field">Nome fantasia<input name="trade_name" value="<?=e($profile['trade_name']??$seller['trade_name']??'')?>"></label><label class="settings-field">CPF/CNPJ<input name="document" required maxlength="40" value="<?=e($profile['document']??$seller['document']??'')?>"><small>Tratado como texto para CNPJ alfanumérico.</small></label>
<label class="settings-field">Indicador IE<select name="state_registration_indicator"><option value="contributor" <?=($profile['state_registration_indicator']??'contributor')==='contributor'?'selected':''?>>Contribuinte</option><option value="exempt" <?=($profile['state_registration_indicator']??'')==='exempt'?'selected':''?>>Isento</option><option value="non_contributor" <?=($profile['state_registration_indicator']??'')==='non_contributor'?'selected':''?>>Não contribuinte</option></select></label>
<label class="settings-field">Inscrição estadual<input name="state_registration" value="<?=e($profile['state_registration']??$seller['state_registration']??'')?>"></label><label class="settings-field">Inscrição municipal<input name="municipal_registration" value="<?=e($profile['municipal_registration']??'')?>"></label><label class="settings-field">Regime tributário<input name="tax_regime" value="<?=e($profile['tax_regime']??'')?>"></label><label class="settings-field">CRT<input name="crt" maxlength="4" value="<?=e($profile['crt']??'')?>"></label><label class="settings-field">Série NF-e<input name="nfe_series" type="number" min="1" max="999" value="<?=e($profile['nfe_series']??1)?>"></label><label class="settings-field">E-mail fiscal<input name="fiscal_email" type="email" value="<?=e($profile['fiscal_email']??$seller['user_email']??'')?>"></label>
</div></section>
<section class="settings-card"><header><span>03</span><div><h3>Endereço fiscal</h3><p>Obrigatório quando a emissão for realizada pela própria Tuffer.</p></div></header><div class="settings-grid"><label class="settings-field">CEP<input name="postal_code" maxlength="8" value="<?=e($profile['postal_code']??'')?>"></label><label class="settings-field">Logradouro<input name="street" value="<?=e($profile['street']??'')?>"></label><label class="settings-field">Número<input name="number" value="<?=e($profile['number']??'')?>"></label><label class="settings-field">Complemento<input name="complement" value="<?=e($profile['complement']??'')?>"></label><label class="settings-field">Bairro<input name="neighborhood" value="<?=e($profile['neighborhood']??'')?>"></label><label class="settings-field">Município<input name="city" value="<?=e($profile['city']??'')?>"></label><label class="settings-field">UF<input name="state" maxlength="2" value="<?=e($profile['state']??'')?>"></label><label class="settings-field">Código IBGE<input name="city_ibge_code" maxlength="7" pattern="\d{7}" value="<?=e($profile['city_ibge_code']??'')?>"></label></div><footer class="settings-savebar"><span><i></i> Certificados, tokens e senhas continuam fora deste cadastro.</span><button class="button button--primary">Salvar configuração desta loja</button></footer></section></form>
<section class="settings-card"><header><span>04</span><div><h3>Classificação fiscal dos produtos</h3><p>Necessária para emissão pela Tuffer; pode ser mantida mesmo quando a loja usa ERP externo.</p></div></header><?php if(!$products):?><p>Nenhum produto cadastrado.</p><?php endif;?><?php foreach($products as $p):?><form id="produto-<?=(int)$p['id']?>" class="settings-form" method="post" action="<?=e(url('/vendedor/fiscal/produtos/'.(int)$p['id']))?>" style="margin-bottom:24px"><?=csrf_field()?><h4><?=e($p['name'])?> <small>· SKU <?=e($p['sku']??'sem SKU')?></small></h4><div class="settings-grid"><label class="settings-field">NCM<input name="ncm" maxlength="8" value="<?=e($p['ncm']??'')?>"></label><label class="settings-field">CEST<input name="cest" maxlength="7" value="<?=e($p['cest']??'')?>"></label><label class="settings-field">Origem<input name="origin" type="number" min="0" max="8" value="<?=e(isset($p['origin'])?(string)$p['origin']:'')?>"></label><label class="settings-field">Unidade comercial<input name="commercial_unit" maxlength="6" value="<?=e($p['commercial_unit']??'UN')?>"></label><label class="settings-field">Unidade tributável<input name="tributary_unit" maxlength="6" value="<?=e($p['tributary_unit']??'UN')?>"></label><label class="settings-field">GTIN/EAN<input name="gtin" maxlength="20" value="<?=e($p['gtin']??'')?>"></label><label class="settings-field">CFOP dentro UF<input name="cfop_in_state" maxlength="4" value="<?=e($p['cfop_in_state']??'')?>"></label><label class="settings-field">CFOP fora UF<input name="cfop_out_state" maxlength="4" value="<?=e($p['cfop_out_state']??'')?>"></label><label class="settings-field">ICMS/CSOSN<input name="icms_code" maxlength="4" value="<?=e($p['icms_code']??'')?>"></label><label class="settings-field">PIS<input name="pis_code" maxlength="4" value="<?=e($p['pis_code']??'')?>"></label><label class="settings-field">COFINS<input name="cofins_code" maxlength="4" value="<?=e($p['cofins_code']??'')?>"></label><label class="settings-field">IPI<input name="ipi_code" maxlength="4" value="<?=e($p['ipi_code']??'')?>"></label><label class="settings-field">CST IBS/CBS<input name="ibs_cbs_cst" maxlength="4" value="<?=e($p['ibs_cbs_cst']??'')?>"></label><label class="settings-field">Classificação IBS/CBS<input name="ibs_cbs_classification" maxlength="20" value="<?=e($p['ibs_cbs_classification']??'')?>"></label></div><button class="button button--secondary">Salvar fiscal do produto</button></form><?php endforeach;?></section>
<section class="settings-card" id="documentos"><header><span>05</span><div><h3>Documentos recentes</h3><p>Independentemente do emissor, a NF-e fica vinculada ao <code>seller_order</code>.</p></div></header><div class="table-responsive"><table class="data-table"><thead><tr><th>Pedido</th><th>Modo</th><th>Status</th><th>Número</th><th>Chave / ação</th></tr></thead><tbody><?php if(!$documents):?><tr><td colspan="5">Nenhum documento fiscal.</td></tr><?php endif;?><?php foreach($documents as $d):?><tr><td><?=e($d['seller_order_code'])?></td><td><?=e(str_replace('_',' ',(string)($d['issuance_mode']??'platform')))?></td><td><?=e(str_replace('_',' ',(string)$d['status']))?></td><td><?=$d['number']?e((string)$d['number']):'—'?></td><td><?php if($d['access_key']):?><?=e((string)$d['access_key'])?><?php elseif(in_array((string)$d['status'],['awaiting_manual','awaiting_external'],true)):?><form method="post" action="<?=e(url('/vendedor/fiscal/documentos/'.(int)$d['seller_order_id'].'/registrar'))?>" class="settings-form"><?=csrf_field()?><div class="settings-grid"><label class="settings-field">Número<input name="number" type="number" min="1" required></label><label class="settings-field">Série<input name="series" type="number" min="1" max="999" value="<?=e((string)($d['series']??1))?>" required></label><label class="settings-field">Chave NF-e<input name="access_key" maxlength="44" pattern="\d{44}" required></label><label class="settings-field">Protocolo<input name="protocol"></label><label class="settings-field">Referência externa<input name="external_reference"></label></div><button class="button button--secondary">Vincular NF-e</button></form><?php elseif(!empty($d['requires_action'])):?><?=e((string)($d['action_reason']??'Revisão necessária'))?><?php else:?>—<?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
