<header class="commerce-hero commerce-hero--seller">
    <div>
        <span class="eyebrow">MÓDULO FISCAL</span>
        <h2>Fiscal da loja</h2>
        <p>A emissão é responsabilidade da própria loja. A Tuffer mantém a NF-e vinculada ao pedido e disponível para operação e cliente.</p>
    </div>
    <div class="seller-identity">
        <span>NF</span>
        <div><strong><?=e($currentStore['name'])?></strong><small><?=e($fiscalMode)?> · <?=e($fiscalProvider)?></small></div>
    </div>
</header>

<div class="settings-note"><span>!</span><p>A Tuffer não transmite NF-e à SEFAZ. <?php if($fiscalMode==='manual'):?>Esta loja emite no sistema de sua preferência e registra a nota na Tuffer.<?php else:?>O sistema/ERP escolhido pela loja devolve os dados da NF-e para a Tuffer pela API.<?php endif;?></p></div>

<?php if(($profile['profile_source']??'')==='seller_fallback'):?><div class="settings-note"><span>i</span><p>Esta loja ainda usa o cadastro fiscal antigo do vendedor como referência. Ao salvar, será criado um perfil fiscal próprio para esta loja.</p></div><?php endif;?>

<form class="settings-form" method="post" action="<?=e(url('/vendedor/fiscal/perfil'))?>"><?=csrf_field()?>
<section class="settings-card"><header><span>01</span><div><h3>Como esta loja informa a NF-e?</h3><p>Cada loja pode usar o emissor, ERP ou processo fiscal que já possui.</p></div></header><div class="settings-grid">
<label class="settings-field">Acompanhamento fiscal<select name="enabled"><option value="0" <?=empty($profile['enabled'])?'selected':''?>>Desabilitado</option><option value="1" <?=!empty($profile['enabled'])?'selected':''?>>Habilitado</option></select></label>
<label class="settings-field">Modo<select name="issuance_mode"><option value="manual" <?=$fiscalMode==='manual'?'selected':''?>>Registro manual</option><option value="external" <?=$fiscalMode==='external'?'selected':''?>>Integração externa / ERP</option></select><small>Não existe emissão “pela Tuffer”.</small></label>
<label class="settings-field">Sistema emissor / integração<select name="provider"><?php $selectedProvider=(string)$fiscalProvider;foreach(['manual'=>'Registro manual','focus'=>'Focus NFe da loja','nuvem_fiscal'=>'Nuvem Fiscal da loja','plugnotas'=>'PlugNotas da loja','erp'=>'ERP próprio','external'=>'API externa','custom'=>'Outro sistema'] as $value=>$label):?><option value="<?=e($value)?>" <?=$selectedProvider===$value?'selected':''?>><?=e($label)?></option><?php endforeach;?></select><small>Este campo identifica o sistema usado pela loja; a Tuffer não utiliza a credencial desse provider para emitir.</small></label>
<label class="settings-field">Ambiente do sistema externo<select name="environment"><option value="homologation" <?=$fiscalEnvironment==='homologation'?'selected':''?>>Homologação</option><option value="production" <?=$fiscalEnvironment==='production'?'selected':''?>>Produção</option></select></label>
</div><footer class="settings-savebar"><span><i></i> Tokens e certificados do emissor permanecem sob responsabilidade da loja.</span><a class="button button--secondary" href="<?=e(url('/vendedor/fiscal/integracao'))?>">Integração / documentos</a></footer></section>

<section class="settings-card"><header><span>02</span><div><h3>Identificação fiscal da loja</h3><p>Esses dados identificam quem emitiu a NF-e e podem variar entre estabelecimentos.</p></div></header><div class="settings-grid">
<label class="settings-field">Razão social<input name="legal_name" required value="<?=e($profile['legal_name']??$seller['legal_name']??'')?>"></label><label class="settings-field">Nome fantasia<input name="trade_name" value="<?=e($profile['trade_name']??$seller['trade_name']??'')?>"></label><label class="settings-field">CPF/CNPJ<input name="document" required maxlength="40" value="<?=e($profile['document']??$seller['document']??'')?>"><small>Tratado como texto para suportar CNPJ alfanumérico.</small></label>
<label class="settings-field">Indicador IE<select name="state_registration_indicator"><option value="contributor" <?=($profile['state_registration_indicator']??'contributor')==='contributor'?'selected':''?>>Contribuinte</option><option value="exempt" <?=($profile['state_registration_indicator']??'')==='exempt'?'selected':''?>>Isento</option><option value="non_contributor" <?=($profile['state_registration_indicator']??'')==='non_contributor'?'selected':''?>>Não contribuinte</option></select></label>
<label class="settings-field">Inscrição estadual<input name="state_registration" value="<?=e($profile['state_registration']??$seller['state_registration']??'')?>"></label><label class="settings-field">Inscrição municipal<input name="municipal_registration" value="<?=e($profile['municipal_registration']??'')?>"></label><label class="settings-field">Regime tributário<input name="tax_regime" value="<?=e($profile['tax_regime']??'')?>"></label><label class="settings-field">CRT<input name="crt" maxlength="4" value="<?=e($profile['crt']??'')?>"></label><label class="settings-field">Série padrão NF-e<input name="nfe_series" type="number" min="1" max="999" value="<?=e($profile['nfe_series']??1)?>"></label><label class="settings-field">E-mail fiscal<input name="fiscal_email" type="email" value="<?=e($profile['fiscal_email']??$seller['user_email']??'')?>"></label>
</div></section>

<section class="settings-card"><header><span>03</span><div><h3>Endereço fiscal</h3><p>Cadastro de referência do estabelecimento emissor. A tributação e a emissão continuam sendo responsabilidade do sistema da loja.</p></div></header><div class="settings-grid"><label class="settings-field">CEP<input name="postal_code" maxlength="8" value="<?=e($profile['postal_code']??'')?>"></label><label class="settings-field">Logradouro<input name="street" value="<?=e($profile['street']??'')?>"></label><label class="settings-field">Número<input name="number" value="<?=e($profile['number']??'')?>"></label><label class="settings-field">Complemento<input name="complement" value="<?=e($profile['complement']??'')?>"></label><label class="settings-field">Bairro<input name="neighborhood" value="<?=e($profile['neighborhood']??'')?>"></label><label class="settings-field">Município<input name="city" value="<?=e($profile['city']??'')?>"></label><label class="settings-field">UF<input name="state" maxlength="2" value="<?=e($profile['state']??'')?>"></label><label class="settings-field">Código IBGE<input name="city_ibge_code" maxlength="7" pattern="\d{7}" value="<?=e($profile['city_ibge_code']??'')?>"></label></div><footer class="settings-savebar"><span><i></i> A Tuffer não armazena certificado A1 nem senha do emissor.</span><button class="button button--primary">Salvar configuração desta loja</button></footer></section></form>

<section class="settings-card"><header><span>04</span><div><h3>Referência fiscal dos produtos</h3><p>Campos opcionais para organização e integração. O sistema fiscal da loja continua sendo a fonte responsável pelo cálculo tributário e pela emissão.</p></div></header><?php if(!$products):?><p>Nenhum produto cadastrado.</p><?php endif;?><?php foreach($products as $p):?><form id="produto-<?=(int)$p['id']?>" class="settings-form" method="post" action="<?=e(url('/vendedor/fiscal/produtos/'.(int)$p['id']))?>" style="margin-bottom:24px"><?=csrf_field()?><h4><?=e($p['name'])?> <small>· SKU <?=e($p['sku']??'sem SKU')?></small></h4><div class="settings-grid"><label class="settings-field">NCM<input name="ncm" maxlength="8" value="<?=e($p['ncm']??'')?>"></label><label class="settings-field">CEST<input name="cest" maxlength="7" value="<?=e($p['cest']??'')?>"></label><label class="settings-field">Origem<input name="origin" type="number" min="0" max="8" value="<?=e(isset($p['origin'])?(string)$p['origin']:'')?>"></label><label class="settings-field">Unidade comercial<input name="commercial_unit" maxlength="6" value="<?=e($p['commercial_unit']??'UN')?>"></label><label class="settings-field">Unidade tributável<input name="tributary_unit" maxlength="6" value="<?=e($p['tributary_unit']??'UN')?>"></label><label class="settings-field">GTIN/EAN<input name="gtin" maxlength="20" value="<?=e($p['gtin']??'')?>"></label><label class="settings-field">CFOP dentro UF<input name="cfop_in_state" maxlength="4" value="<?=e($p['cfop_in_state']??'')?>"></label><label class="settings-field">CFOP fora UF<input name="cfop_out_state" maxlength="4" value="<?=e($p['cfop_out_state']??'')?>"></label><label class="settings-field">ICMS/CSOSN<input name="icms_code" maxlength="4" value="<?=e($p['icms_code']??'')?>"></label><label class="settings-field">PIS<input name="pis_code" maxlength="4" value="<?=e($p['pis_code']??'')?>"></label><label class="settings-field">COFINS<input name="cofins_code" maxlength="4" value="<?=e($p['cofins_code']??'')?>"></label><label class="settings-field">IPI<input name="ipi_code" maxlength="4" value="<?=e($p['ipi_code']??'')?>"></label><label class="settings-field">CST IBS/CBS<input name="ibs_cbs_cst" maxlength="4" value="<?=e($p['ibs_cbs_cst']??'')?>"></label><label class="settings-field">Classificação IBS/CBS<input name="ibs_cbs_classification" maxlength="20" value="<?=e($p['ibs_cbs_classification']??'')?>"></label></div><button class="button button--secondary">Salvar referência fiscal</button></form><?php endforeach;?></section>

<section class="settings-card" id="documentos"><header><span>05</span><div><h3>Documentos recentes</h3><p>A Tuffer acompanha a NF-e emitida pela loja e mantém o documento associado ao <code>seller_order</code>.</p></div></header><div class="table-responsive"><table class="data-table"><thead><tr><th>Pedido</th><th>Modo</th><th>Status</th><th>Número</th><th>Chave / ação</th></tr></thead><tbody><?php if(!$documents):?><tr><td colspan="5">Nenhum documento fiscal.</td></tr><?php endif;?><?php foreach($documents as $d):?><tr><td><?=e($d['seller_order_code'])?></td><td><?=e(str_replace('_',' ',(string)($d['issuance_mode']??'manual')))?></td><td><?=e(str_replace('_',' ',(string)$d['status']))?></td><td><?=$d['number']?e((string)$d['number']):'—'?></td><td><?php if($d['access_key']):?><?=e((string)$d['access_key'])?><?php elseif(in_array((string)$d['status'],['awaiting_manual','awaiting_external'],true)):?><form method="post" action="<?=e(url('/vendedor/fiscal/documentos/'.(int)$d['seller_order_id'].'/registrar'))?>" class="settings-form"><?=csrf_field()?><div class="settings-grid"><label class="settings-field">Número<input name="number" type="number" min="1" required></label><label class="settings-field">Série<input name="series" type="number" min="1" max="999" value="<?=e((string)($d['series']??1))?>" required></label><label class="settings-field">Chave NF-e<input name="access_key" maxlength="44" pattern="\d{44}" required></label><label class="settings-field">Protocolo<input name="protocol"></label><label class="settings-field">Referência externa<input name="external_reference"></label></div><button class="button button--secondary">Vincular NF-e</button></form><?php elseif(!empty($d['requires_action'])):?><?=e((string)($d['action_reason']??'Revisão necessária'))?><?php else:?>—<?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
