<header class="commerce-hero commerce-hero--seller"><div><span class="eyebrow">FISCAL · INTEGRAÇÃO</span><h2>ERP e documentos fiscais</h2><p>Conecte o emissor da loja à Tuffer ou registre NF-e emitida fora da plataforma.</p></div><div class="seller-identity"><span>API</span><div><strong><?=e($currentStore['name'])?></strong><small><?=e((string)($profile['issuance_mode']??'não configurado'))?></small></div></div></header>
<p><a class="button button--secondary" href="<?=e(url('/vendedor/fiscal'))?>">← Voltar ao Fiscal</a> <?php if(($profile['issuance_mode']??'')==='external'):?><a class="button button--primary" href="<?=e(url('/vendedor/fiscal/webhook'))?>">Configurar automação →</a><?php endif;?></p>
<?php if(!$profile):?><div class="settings-note"><span>!</span><p>Salve primeiro a configuração fiscal desta loja.</p></div><?php endif;?>
<?php if(($profile['issuance_mode']??'')==='external'):?>
<section class="settings-card"><header><span>01</span><div><h3>Credencial do ERP</h3><p>O segredo completo aparece somente no momento da geração.</p></div></header>
<?php if($generatedToken):?><div class="settings-note"><span>!</span><p>Copie agora o token: <code style="word-break:break-all"><?=e($generatedToken)?></code></p></div><?php endif;?>
<div class="settings-grid"><div class="settings-field"><strong>Endpoint base</strong><code><?=e(url('/api/v1/fiscal'))?></code></div><div class="settings-field"><strong>Autenticação</strong><code>Authorization: Bearer tf_fiscal_...</code></div><div class="settings-field"><strong>Credencial atual</strong><span><?=e($credential['token_prefix']??'Nenhuma')?><?=!empty($credential)?'…':''?></span></div><div class="settings-field"><strong>Status</strong><span><?=!empty($credential['enabled'])&&empty($credential['revoked_at'])?'Ativa':'Inativa'?></span></div><div class="settings-field"><strong>Último uso</strong><span><?=e((string)($credential['last_used_at']??'Nunca'))?></span></div></div>
<footer class="settings-savebar"><form method="post" action="<?=e(url('/vendedor/fiscal/integracao/token'))?>"><?=csrf_field()?><button class="button button--primary"><?=empty($credential)?'Gerar token':'Rotacionar token'?></button></form><?php if(!empty($credential['enabled'])&&empty($credential['revoked_at'])):?><form method="post" action="<?=e(url('/vendedor/fiscal/integracao/token/revogar'))?>"><?=csrf_field()?><button class="button button--secondary">Revogar token</button></form><?php endif;?></footer>
<p><code>GET /seller-orders/{code}</code> consulta documento · <code>GET /seller-orders/{code}/payload</code> dados completos para emissão · <code>POST /authorize</code> registra autorização · <code>POST /cancel</code> registra cancelamento.</p></section>
<?php endif;?>
<section class="settings-card" id="documentos"><header><span><?=($profile['issuance_mode']??'')==='external'?'02':'01'?></span><div><h3>Documentos emitidos fora da Tuffer</h3><p>XML e DANFE são guardados no storage privado.</p></div></header><div class="table-responsive"><table class="data-table"><thead><tr><th>Pedido</th><th>Modo</th><th>Status</th><th>NF-e</th><th>Ações</th></tr></thead><tbody>
<?php if(!$documents):?><tr><td colspan="5">Nenhum documento fiscal externo nesta loja.</td></tr><?php endif;?>
<?php foreach($documents as $d):?><tr><td><?=e($d['seller_order_code'])?></td><td><?=e((string)$d['issuance_mode'])?></td><td><?=e(str_replace('_',' ',(string)$d['status']))?></td><td><?php if($d['access_key']):?>Nº <?=e((string)$d['number'])?> · série <?=e((string)$d['series'])?><br><small style="word-break:break-all"><?=e((string)$d['access_key'])?></small><?php else:?>—<?php endif;?></td><td>
<?php if(in_array((string)$d['status'],['awaiting_manual','awaiting_external'],true)):?><form enctype="multipart/form-data" method="post" action="<?=e(url('/vendedor/fiscal/integracao/documentos/'.(int)$d['seller_order_id'].'/registrar'))?>"><?=csrf_field()?><div class="settings-grid"><label class="settings-field">Número<input name="number" type="number" min="1" required></label><label class="settings-field">Série<input name="series" type="number" min="1" max="999" value="<?=e((string)($d['series']??1))?>" required></label><label class="settings-field">Chave<input name="access_key" maxlength="44" pattern="\d{44}" required></label><label class="settings-field">Protocolo<input name="protocol"></label><label class="settings-field">Referência externa<input name="external_reference"></label><label class="settings-field">XML<input type="file" name="xml" accept=".xml,application/xml,text/xml"></label><label class="settings-field">DANFE<input type="file" name="danfe" accept=".pdf,application/pdf"></label></div><button class="button button--secondary">Registrar NF-e</button></form><?php endif;?>
<?php if(in_array((string)$d['status'],['authorized','cancelled'],true)&&(!$d['xml_storage_path']||!$d['danfe_storage_path'])):?><form enctype="multipart/form-data" method="post" action="<?=e(url('/vendedor/fiscal/integracao/documentos/'.(int)$d['seller_order_id'].'/arquivos'))?>"><?=csrf_field()?><label>XML <input type="file" name="xml" accept=".xml,application/xml,text/xml"></label> <label>DANFE <input type="file" name="danfe" accept=".pdf,application/pdf"></label><button class="button button--secondary">Anexar arquivos</button></form><?php endif;?>
<?php if((string)$d['status']==='authorized'):?><form method="post" action="<?=e(url('/vendedor/fiscal/integracao/documentos/'.(int)$d['seller_order_id'].'/cancelar'))?>"><?=csrf_field()?><label>Motivo <input name="reason" minlength="15" maxlength="1000" required></label><label>Protocolo <input name="cancellation_protocol"></label><button class="button button--secondary">Registrar cancelamento</button></form><?php elseif((string)$d['status']==='cancelled'):?><small>Cancelada: <?=e((string)($d['cancellation_reason']??'motivo não informado'))?></small><?php endif;?>
</td></tr><?php endforeach;?></tbody></table></div></section>
