<header class="commerce-hero commerce-hero--seller"><div><span class="eyebrow">FISCAL · CONECTOR</span><h2>Tiny / Olist ERP</h2><p>Conecte a conta fiscal desta loja para enviar pedidos pagos e acompanhar a NF-e automaticamente.</p></div><div class="seller-identity"><span>TY</span><div><strong><?=e($currentStore['name'])?></strong><small><?=!empty($connector['enabled'])?'conectado':'não conectado'?></small></div></div></header>
<p><a class="button button--secondary" href="<?=e(url('/vendedor/fiscal'))?>">← Voltar ao Fiscal</a></p>
<div class="settings-note"><span>i</span><p>A Tuffer não usa certificado A1 da loja. A emissão ocorre dentro da conta Tiny/Olist do vendedor usando o token desta própria conta. O CPF/CNPJ retornado pelo Tiny precisa corresponder ao documento fiscal da loja.</p></div>
<?php if(!$profile):?><div class="settings-note"><span>!</span><p>Salve primeiro os dados fiscais desta loja em Fiscal antes de conectar o Tiny.</p></div><?php endif;?>

<section class="settings-card"><header><span>01</span><div><h3>Conta Tiny desta loja</h3><p>O token é criptografado e nunca volta a ser exibido depois de salvo.</p></div></header>
<?php if($connector):?><div class="settings-grid"><div class="settings-field"><strong>Status</strong><span><?=!empty($connector['enabled'])?'Conectado':'Desconectado'?></span></div><div class="settings-field"><strong>Conta</strong><span><?=e((string)($connector['account_name']??'—'))?></span></div><div class="settings-field"><strong>CPF/CNPJ</strong><span><?=e((string)($connector['account_document']??'—'))?></span></div><div class="settings-field"><strong>Token salvo</strong><code><?=e((string)($connector['credential_prefix']??'—'))?></code></div><div class="settings-field"><strong>Último teste</strong><span><?=e((string)($connector['last_test_at']??'Nunca'))?></span></div><div class="settings-field"><strong>Último sucesso</strong><span><?=e((string)($connector['last_success_at']??'Nunca'))?></span></div><?php if(!empty($connector['last_error'])):?><div class="settings-field"><strong>Último erro</strong><span><?=e((string)$connector['last_error'])?></span></div><?php endif;?></div><?php endif;?>
<form class="settings-form" method="post" action="<?=e(url('/vendedor/fiscal/conectores/tiny/conectar'))?>"><?=csrf_field()?><div class="settings-grid"><label class="settings-field">Token API Tiny<input type="password" name="token" autocomplete="off" required placeholder="Cole o token da conta desta loja"><small>Ao salvar um novo token, a credencial anterior é substituída.</small></label><label class="settings-field">Automação<label><input type="checkbox" name="auto_emit" value="1" <?=empty($connector)||!empty($connector['auto_emit'])?'checked':''?>> Gerar e solicitar emissão da NF-e automaticamente</label><small>Desmarcado: a Tuffer cria a NF-e no Tiny e aguarda você emitir no próprio Tiny.</small></label><label class="settings-field">E-mail pelo Tiny<label><input type="checkbox" name="send_email" value="1" <?=!empty($connector['send_email'])?'checked':''?>> Pedir ao Tiny para enviar a NF-e ao e-mail do cliente</label></label></div><footer class="settings-savebar"><span><i></i> A conexão é exclusiva desta loja.</span><button class="button button--primary" <?=$profile?'':'disabled'?>><?=!empty($connector['enabled'])?'Atualizar conexão':'Conectar Tiny'?></button></footer></form>
<?php if(!empty($connector['enabled'])):?><footer class="settings-savebar"><form method="post" action="<?=e(url('/vendedor/fiscal/conectores/tiny/testar'))?>"><?=csrf_field()?><button class="button button--secondary">Testar conexão</button></form><form method="post" action="<?=e(url('/vendedor/fiscal/conectores/tiny/desconectar'))?>"><?=csrf_field()?><button class="button button--secondary">Desconectar Tiny</button></form></footer><?php endif;?></section>

<section class="settings-card"><header><span>02</span><div><h3>Fluxo automático</h3><p>Depois do pagamento, cada seller_order desta loja é tratado de forma independente.</p></div></header><div class="settings-grid"><div class="settings-field"><strong>1</strong><span>Tuffer procura o pedido no Tiny pelo código do seller_order.</span></div><div class="settings-field"><strong>2</strong><span>Se não existir, cria o pedido como aprovado.</span></div><div class="settings-field"><strong>3</strong><span>Procura ou gera a NF-e vinculada ao pedido.</span></div><div class="settings-field"><strong>4</strong><span>Solicita emissão e acompanha a autorização.</span></div><div class="settings-field"><strong>5</strong><span>Chave e XML autorizados voltam para o pedido na Tuffer.</span></div></div></section>

<section class="settings-card"><header><span>03</span><div><h3>Sincronizações recentes</h3><p>Histórico operacional do conector Tiny desta loja.</p></div></header><div class="table-responsive"><table class="data-table"><thead><tr><th>Pedido</th><th>Status</th><th>Pedido Tiny</th><th>NF-e Tiny</th><th>NF-e Tuffer</th><th>Ação</th></tr></thead><tbody><?php if(!$runs):?><tr><td colspan="6">Nenhuma sincronização Tiny ainda.</td></tr><?php endif;?><?php foreach($runs as $r):?><tr><td><?=e((string)$r['seller_order_code'])?></td><td><?=e(str_replace('_',' ',(string)$r['status']))?><?php if(!empty($r['last_error'])):?><br><small><?=e((string)$r['last_error'])?></small><?php endif;?></td><td><?=e((string)($r['provider_order_number']?:$r['provider_order_id']?:'—'))?></td><td><?=e((string)($r['provider_document_number']?:$r['provider_document_id']?:'—'))?><?php if(!empty($r['provider_status'])):?><br><small><?=e((string)$r['provider_status'])?></small><?php endif;?><?php if(!empty($r['provider_document_url'])&&str_starts_with((string)$r['provider_document_url'],'https://tiny.com.br/')):?><br><a href="<?=e((string)$r['provider_document_url'])?>" target="_blank" rel="noopener noreferrer">Abrir no Tiny</a><?php endif;?></td><td><?php if(!empty($r['access_key'])):?>Nº <?=e((string)$r['number'])?> · série <?=e((string)$r['series'])?><br><small style="word-break:break-all"><?=e((string)$r['access_key'])?></small><?php else:?><?=e(str_replace('_',' ',(string)$r['document_status']))?><?php endif;?></td><td><?php if((string)$r['status']!=='completed'):?><form method="post" action="<?=e(url('/vendedor/fiscal/conectores/tiny/processar/'.(int)$r['id']))?>"><?=csrf_field()?><button class="button button--secondary">Reprocessar</button></form><?php else:?>Concluído<?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
