<header class="commerce-hero commerce-hero--seller"><div><span class="eyebrow">FISCAL · WEBHOOK</span><h2>Automação com o ERP</h2><p>A Tuffer avisa seu sistema quando um pedido estiver pronto para emissão. A emissão continua sendo feita exclusivamente pelo emissor da sua loja.</p></div><div class="seller-identity"><span>HMAC</span><div><strong><?=e($currentStore['name'])?></strong><small><?=!empty($webhook['enabled'])?'Webhook ativo':'Webhook inativo'?></small></div></div></header>
<p><a class="button button--secondary" href="<?=e(url('/vendedor/fiscal/integracao'))?>">← Voltar à Integração fiscal</a></p>

<?php if(($profile['issuance_mode']??'')!=='external'):?><div class="settings-note"><span>!</span><p>Para usar o fluxo automático, configure esta loja no modo Integração externa / ERP.</p></div><?php endif;?>

<section class="settings-card"><header><span>01</span><div><h3>Endpoint do seu ERP</h3><p>Somente HTTPS público na porta 443. URLs locais, privadas e reservadas são bloqueadas.</p></div></header>
<?php if($generatedWebhookSecret):?><div class="settings-note"><span>!</span><p>Copie agora o segredo HMAC: <code style="word-break:break-all"><?=e($generatedWebhookSecret)?></code><br>Ele não será exibido novamente. Ao salvar uma nova URL, o segredo é rotacionado.</p></div><?php endif;?>
<form method="post" action="<?=e(url('/vendedor/fiscal/webhook'))?>"><?=csrf_field()?><div class="settings-grid"><label class="settings-field">URL HTTPS do webhook<input type="url" name="endpoint_url" maxlength="2048" placeholder="https://erp.exemplo.com/webhooks/tuffer" value="<?=e((string)($webhook['endpoint_url']??''))?>" required></label><div class="settings-field"><strong>Segredo atual</strong><span><?=e((string)($webhook['secret_prefix']??'Nenhum'))?><?=!empty($webhook)?'…':''?></span></div><div class="settings-field"><strong>Status</strong><span><?=!empty($webhook['enabled'])?'Ativo':'Inativo'?></span></div><div class="settings-field"><strong>Último sucesso</strong><span><?=e((string)($webhook['last_success_at']??'Nunca'))?></span></div><div class="settings-field"><strong>Última falha</strong><span><?=e((string)($webhook['last_failure_at']??'Nunca'))?></span></div><div class="settings-field"><strong>Último HTTP</strong><span><?=e((string)($webhook['last_http_status']??'—'))?></span></div></div><footer class="settings-savebar"><button class="button button--primary" <?=($profile['issuance_mode']??'')!=='external'?'disabled':''?>><?=empty($webhook)?'Ativar webhook':'Salvar e rotacionar segredo'?></button></footer></form>
<?php if(!empty($webhook['enabled'])):?><form method="post" action="<?=e(url('/vendedor/fiscal/webhook/desativar'))?>"><?=csrf_field()?><button class="button button--secondary">Desativar webhook</button></form><?php endif;?>
<?php if(!empty($webhook['last_error'])):?><div class="settings-note"><span>!</span><p><?=e((string)$webhook['last_error'])?></p></div><?php endif;?>
</section>

<section class="settings-card"><header><span>02</span><div><h3>Contrato do evento</h3><p>O webhook é apenas um aviso. O ERP usa o token Bearer da loja para buscar o payload fiscal completo.</p></div></header>
<div class="settings-grid"><div class="settings-field"><strong>Evento</strong><code>fiscal.seller_order.ready</code></div><div class="settings-field"><strong>Payload</strong><code>GET /api/v1/fiscal/seller-orders/{code}/payload</code></div><div class="settings-field"><strong>Retorno da NF-e</strong><code>POST /api/v1/fiscal/seller-orders/{code}/authorize</code></div><div class="settings-field"><strong>Cancelamento</strong><code>POST /api/v1/fiscal/seller-orders/{code}/cancel</code></div></div>
<p>Assine/valide o corpo bruto com <code>HMAC-SHA256</code> usando <code>timestamp.body</code>. Headers: <code>X-Tuffer-Event</code>, <code>X-Tuffer-Timestamp</code> e <code>X-Tuffer-Signature: sha256=...</code>.</p>
</section>

<section class="settings-card"><header><span>03</span><div><h3>Últimas entregas</h3><p>A Tuffer reprocessa falhas automaticamente pela fila fiscal.</p></div></header><div class="table-responsive"><table class="data-table"><thead><tr><th>Evento</th><th>Pedido</th><th>Status</th><th>Tentativas</th><th>HTTP</th><th>Data</th></tr></thead><tbody><?php if(!$deliveries):?><tr><td colspan="6">Nenhum webhook fiscal enviado ainda.</td></tr><?php endif;?><?php foreach($deliveries as $d):?><tr><td><code><?=e((string)$d['event_type'])?></code><br><small><?=e((string)$d['event_id'])?></small></td><td>#<?=e((string)$d['seller_order_id'])?></td><td><?=e((string)$d['status'])?></td><td><?=e((string)$d['attempts'])?></td><td><?=e((string)($d['http_status']??'—'))?></td><td><?=e((string)$d['created_at'])?></td></tr><?php endforeach;?></tbody></table></div></section>
