<div class="dashboard-heading catalog-heading"><div><span class="eyebrow">CATÁLOGO</span><h2>Categorias</h2><p>Organize a hierarquia e escolha quais categorias ganham espaço na navegação e na home.</p></div><a class="button button--primary" href="<?= e(url('/admin/categorias/nova')) ?>">+ Criar categoria</a></div>

<section class="category-admin-metrics" aria-label="Resumo das categorias"><article><span>Total</span><strong><?= (int) $metrics['total'] ?></strong><small>categorias cadastradas</small></article><article><span>Ativas</span><strong><?= (int) $metrics['active'] ?></strong><small>disponíveis para gestão</small></article><article><span>Na home</span><strong><?= (int) $metrics['home'] ?></strong><small>selecionadas manualmente</small></article><article><span>Com imagem</span><strong><?= (int) $metrics['with_image'] ?></strong><small>prontas para vitrines</small></article></section>

<?php if ($categories): ?><section class="category-admin-grid">
    <?php foreach ($categories as $category): ?>
        <article class="category-admin-card <?= $category['status'] !== 'active' ? 'is-inactive' : '' ?>">
            <div class="category-admin-card__image"><?php if (!empty($category['image_path'])): ?><img src="<?= e(upload_asset($category['image_path'])) ?>" alt="" loading="lazy"><?php else: ?><span><?= e(mb_strtoupper(mb_substr($category['name'], 0, 1))) ?></span><small>Sem imagem</small><?php endif; ?><?php if ($category['is_featured']): ?><b>Destaque</b><?php endif; ?></div>
            <div class="category-admin-card__body"><div class="category-admin-card__eyebrow"><span>Nível <?= (int) $category['depth'] + 1 ?></span><i class="<?= $category['status'] === 'active' ? 'is-active' : '' ?>"><?= $category['status'] === 'active' ? 'Ativa' : 'Inativa' ?></i></div><h3><?= e($category['name']) ?></h3><p title="<?= e($category['path']) ?>"><?= e($category['path']) ?></p><code>/<?= e($category['slug']) ?></code><dl><div><dt>Produtos</dt><dd><?= (int) $category['products'] ?></dd></div><div><dt>Subcategorias</dt><dd><?= (int) $category['subcategories'] ?></dd></div><div><dt>Ordem</dt><dd><?= (int) $category['sort_order'] ?></dd></div></dl><div class="category-admin-card__flags"><?php if ($category['show_in_home']): ?><span>Home</span><?php endif; ?><?php if ($category['show_in_menu']): ?><span>Menu</span><?php endif; ?><?php if (!$category['allow_products']): ?><span>Sem produtos</span><?php endif; ?><?php if (!$category['customer_visible']): ?><span>Oculta</span><?php endif; ?></div></div>
            <footer><div class="category-order-actions" aria-label="Alterar ordem"><form method="post" action="<?= e(url('/admin/categorias/' . $category['id'] . '/ordenar')) ?>"><?= csrf_field() ?><input type="hidden" name="direction" value="up"><button type="submit" title="Mover para cima" aria-label="Mover <?= e($category['name']) ?> para cima">↑</button></form><form method="post" action="<?= e(url('/admin/categorias/' . $category['id'] . '/ordenar')) ?>"><?= csrf_field() ?><input type="hidden" name="direction" value="down"><button type="submit" title="Mover para baixo" aria-label="Mover <?= e($category['name']) ?> para baixo">↓</button></form></div><div><?php if ($category['status'] === 'active' && $category['customer_visible']): ?><a href="<?= e(url('/categoria/' . $category['slug'])) ?>" target="_blank" rel="noopener">Visualizar</a><?php endif; ?><a class="button button--secondary" href="<?= e(url('/admin/categorias/' . $category['id'] . '/editar')) ?>">Editar</a></div></footer>
        </article>
    <?php endforeach; ?>
</section><?php else: ?><section class="panel catalog-empty"><strong>Nenhuma categoria cadastrada</strong><p>Crie a primeira categoria para começar a organizar o catálogo.</p><a class="button button--primary" href="<?= e(url('/admin/categorias/nova')) ?>">Criar categoria</a></section><?php endif; ?>
